Click helper enhancement
emberjs/ember.js pull request #14274
Opened 2016-09-13 01:03 UTC by BryanCrotaz

Improve click helper

Note that tests did not pass before the change, so could not verify behaviour.

2016-10-11 05:52 UTC, stefanpenner commented on packages/ember-testing/lib/events.js
> +      screenX: options.screenX || x + 5,
what if the option provided is the coordinate of `0` it will be falsey, and the `||` will fall to the right hand side, is that intentional?

2016-10-11 07:40 UTC, BryanCrotaz commented
Whoops!!

2016-11-08 07:30 UTC, locks requested changes
Please address https://github.com/emberjs/ember.js/pull/14274/files#r82728021 :)

2016-11-13 12:25 UTC, BryanCrotaz commented
@locks addressed

2016-11-14 00:04 UTC, stefanpenner commented on packages/ember-testing/lib/helpers/click.js
> +  @param {Object} event An optional hash of event parameters to mock the JQuery [Event]{@link http://api.jquery.com/category/events/event-object/} object.
this may be considered a new feature, although I could be convinced this is a bugfix

@rwjblue what do you think good sir.

2016-11-14 00:06 UTC, stefanpenner commented on packages/ember-testing/lib/events.js
> +      options.button = 0;
what was the original behavior?

2016-11-14 00:06 UTC, stefanpenner commented on packages/ember-testing/lib/events.js
> +    options.which = options.button + 1; // jquery normalises to 1,2,3 for left, middle, right
what was the original behavior?

2016-11-14 00:18 UTC, stefanpenner commented on packages/ember-testing/lib/events.js
> +    options.which = options.button + 1; // jquery normalises to 1,2,3 for left, middle, right
what was the original behavior? (making sure this isn't a breaking change)

2016-11-14 01:51 UTC, BryanCrotaz commented on packages/ember-testing/lib/events.js
> +    options.which = options.button + 1; // jquery normalises to 1,2,3 for left, middle, right
Always used left button, like it or not. There was no way to test right click

2016-11-14 14:30 UTC, rwjblue commented on packages/ember-testing/lib/helpers/click.js
> +  @param {Object} event An optional hash of event parameters to mock the JQuery [Event]{@link http://api.jquery.com/category/events/event-object/} object.
Yes, likely is adding new functionality / API surface here. I think a quick / short RFC would be good. It does seem like a no brainer to me, but the RFC process helps make sure that we aren't missing obvious things...

2016-11-18 20:01 UTC, pixelhandler commented
@locks did you see the response from @BryanCrotaz yet?

2017-01-27 12:18 UTC, kevinleeleeedds approved these changes

2017-01-27 12:19 UTC, kevinleeleeedds commented
If th th nothing yt? U ight you yt? Your ugh occurring of cm kickoff unblock

2017-01-30 13:32 UTC, locks approved these changes

2017-06-10 18:49 UTC, homu commented
:umbrella: The latest upstream changes (presumably 764e43f) made this pull request unmergeable. Please resolve the merge conflicts.

2018-02-23 04:34 UTC, mmun commented
These enhancements are available in https://github.com/emberjs/ember-test-helpers.

See https://github.com/emberjs/ember-test-helpers/blob/30b135f9f946185918ca6087edc1478ee3ce06ff/addon-test-support/@ember/test-helpers/dom/fire-event.js#L96-L104.

2018-02-23 04:34 UTC, closed without merging