[BUGFIX beta] Remove style warning when the binding is quoted
emberjs/ember.js pull request #14293
Opened 2016-09-14 20:23 UTC by Serabe

Given the following template:

```hbs
<div style="{{myStyle}}"></div>
```

It behaves exactly like:

```hbs
<div style={{myStyle}}></div>
```

Fix #11395

2016-09-15 00:35 UTC, rwjblue requested changes
This looks good, but we need more tests.  Specifically, we need to add tests that ensure things like `style="width: 100px; {{safeStringThingy}}"` warns.

2016-09-15 06:01 UTC, Serabe commented
Thank you for reviewing this, @rwjblue!

I've added three more tests. Let me know if you need me to add anything!

Thank you!

2016-10-10 21:26 UTC, Serabe commented
@rwjblue did I add enough tests? The new tests added in this PR are:

* `<div style="{{userValue}}"></div>` with safe and unsafe strings.
* `<div style="color: green; {{userValue}}"></div>` with safe string.
* `<div style="color: green; width: {{userValue}}"></div>` with safe string.
* `<div style="color: green; {{userProperty}}: 42px"></div>` with safe string.

2016-10-10 21:26 UTC, Serabe commented
Rebased and pushed to check CI

2016-11-03 23:56 UTC, rwjblue approved these changes

2016-11-03 23:56 UTC, merged

2016-11-03 23:56 UTC, rwjblue commented
Thanks @Serabe!