Prevent invalid markup error
emberjs/ember.js pull request #14296
Opened 2016-09-15 08:59 UTC by cbou

I opened an issue some months ago but nobody answered to my example (#12745).

The first link produces a DOMException, the second doesn't.
Both files are identical.

https://charlesbourasseau.com/invalid-markup.xhtml
https://charlesbourasseau.com/invalid-markup.html

Please consider to merge this pull request.

2016-09-15 16:08 UTC, rwjblue approved these changes
It seems slightly annoying to me, but I don't really have any objections or downsides to actually preventing the error here.

I'm generally 👍, but would like @mmun to double check my thought process here.

2016-09-15 16:17 UTC, mmun commented on packages/ember-testing/lib/support.js
> +  $('<input type="checkbox" />')
Can you create the input via DOM APIs instead?

```js
let input = document.createElement('input');
$(input)
  .attr('type', 'checkbox')
  ...
```

2016-09-15 16:21 UTC, mmun commented
@cbou Thanks for reporting! (again... 😓 ). Can you address the comment in the review?

2016-09-15 16:27 UTC, cbou commented
Thanks for answering

2016-09-15 16:34 UTC, mmun commented on packages/ember-testing/lib/support.js
> +  $(input)
Still need the `.attr('type', 'checkbox')`.

2016-09-15 16:38 UTC, mmun commented on packages/ember-testing/lib/support.js
> +  $(input)
Still need the .attr('type', 'checkbox').

2016-09-15 16:38 UTC, mmun requested changes

2016-09-15 17:56 UTC, cbou commented
Oh yes sorry ...

2016-09-15 19:24 UTC, mmun approved these changes

2016-09-15 19:27 UTC, rwjblue requested changes
OK, awesome!  

Can you squash the commits into one, and prefix it with `[BUGFIX beta]`?  I think this will be ready to land once that is done...

2016-09-15 19:40 UTC, cbou commented
I try to squash but I'm not sure this ended well...

2016-09-15 20:29 UTC, rwjblue commented
No problem!  Based on a new feature in GitHub I was able to squash for you, and update your branch.  Once CI finishes this will be good to go.

2016-09-15 20:30 UTC, rwjblue approved these changes

2016-09-16 01:11 UTC, merged

2016-09-16 01:12 UTC, rwjblue commented
Thanks for working through this with us!