Avoid assertion when bound `id` is provided to tagless component
emberjs/ember.js pull request #14385
Opened 2016-09-29 04:39 UTC by HeroicEric

See https://github.com/emberjs/ember.js/pull/14382

/cc @rwjblue

2016-09-30 22:35 UTC, HeroicEric commented
Updated with suggestion from https://github.com/emberjs/ember.js/pull/14382#discussion_r81139229

2016-10-04 13:44 UTC, rwjblue requested changes

2016-10-04 13:44 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/components/fragment-components-test.js
> +    this.runTask(() => set(this.context, 'fooBarId', 'qux'));
Can you do a noop rerender before this mutation step?


This should do the trick:

```
this.assertStableRerender();
```

2016-10-04 14:55 UTC, HeroicEric commented on packages/ember-glimmer/tests/integration/components/fragment-components-test.js
> +    this.runTask(() => set(this.context, 'fooBarId', 'qux'));
done

2016-10-04 15:13 UTC, rwjblue approved these changes

2016-10-04 15:19 UTC, merged

2016-10-04 15:19 UTC, rwjblue commented
Thanks @HeroicEric!