Promise.resolve works with inheritance already
emberjs/ember.js pull request #14426
Opened 2016-10-05 18:44 UTC by stefanpenner

https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/promise/resolve.js#L40

2016-10-05 18:47 UTC, stefanpenner commented on packages/ember-testing/lib/test/promise.js
> -    return run(() => resolve(promise).then(() => value));
i need to look at this more closely

2016-10-06 13:05 UTC, rwjblue requested changes

2016-10-06 13:05 UTC, rwjblue commented on packages/ember-testing/lib/test/promise.js
> +  return TestPromise.resolve(result, label)
@stefanpenner - The tests are failing due to a missing semicolon here.

2016-10-06 22:04 UTC, rwjblue approved these changes

2016-10-06 22:04 UTC, merged