CLI-ify and improve modelFor docs
emberjs/ember.js pull request #14477
Opened 2016-10-14 23:32 UTC by alexspeller

It's generally not a good idea to make stateful changes in validation hooks as
the transition can still get rolled back - this fixes that and also cli-ifys
that part of the doc

2016-10-14 23:36 UTC, locks requested changes
Can you do the whole file? 👼

2016-10-14 23:38 UTC, locks requested changes

2016-10-14 23:38 UTC, locks commented on packages/ember-routing/lib/system/route.js
> +        this.route('comments', { resetNamespace: true });
👎  `resetNamespace`

2016-10-14 23:38 UTC, locks commented on packages/ember-routing/lib/system/route.js
> +      afterModel: function() {
ES2015 `afterModel() {`

2016-10-14 23:38 UTC, locks commented on packages/ember-routing/lib/system/route.js
> +
I'd maybe have two different snippets to make it more evident they're different files.

2016-10-15 19:32 UTC, alexspeller commented
@locks updated the whole file now 👍

2016-10-15 23:08 UTC, locks approved these changes

2016-10-15 23:08 UTC, locks commented
@rwjblue anything necessary to make merging and releasing easier?

2016-10-27 15:31 UTC, merged