Make actions use `target=this` implicitly
emberjs/ember.js pull request #14479
Opened 2016-10-16 06:03 UTC by zackthehuman

This addresses the bug in #14469. Might need a new test. Please review @rwjblue @chancancode.

2016-10-16 15:49 UTC, zackthehuman commented
I added a test.

2016-10-17 17:59 UTC, rwjblue requested changes

2016-10-17 17:59 UTC, rwjblue commented on packages/ember-template-compiler/lib/plugins/transform-action-syntax.js
> + <button {{action target=this 'foo'}}>
This isn't quite right, the hash has to be after positional args...

2016-10-18 01:22 UTC, sukima commented on packages/ember-template-compiler/lib/plugins/transform-action-syntax.js
> + <button onblur={{action target=this (action target=this 'foo') 'bar'}}>
Isn't this also backwards.

2016-10-18 01:22 UTC, sukima commented on packages/ember-template-compiler/lib/plugins/transform-action-syntax.js
> +}
This function is unfortunately repeated. @rwjblue should the util function be DRY somewhere? And if so where?

2016-10-18 01:23 UTC, sukima commented on packages/ember-template-compiler/lib/plugins/transform-action-syntax.js
> +  }
This function is unfortunately repeated. @rwjblue should the util function be DRY somewhere? And if so where?

2016-10-18 04:03 UTC, zackthehuman commented on packages/ember-template-compiler/lib/plugins/transform-action-syntax.js
> +  }
I will extract it and then make another PR to update other refs.

2016-10-18 04:21 UTC, zackthehuman commented on packages/ember-template-compiler/lib/plugins/transform-action-syntax.js
> + <button onblur={{action target=this (action target=this 'foo') 'bar'}}>
Yes; it has been corrected.

2016-10-28 10:26 UTC, Serabe commented
@zackthehuman is this ready for a new review? Thank you!

2016-10-31 04:53 UTC, zackthehuman commented
@Serabe I think we may punt on this due to what was discussed in #14469. Closing for now.

2016-10-31 04:53 UTC, closed without merging

2016-10-31 17:19 UTC, Serabe commented
@zackthehuman thank you!