[BUGFIX beta] Improve behavior for QPs with undefined values
emberjs/ember.js pull request #14537
Opened 2016-10-27 22:17 UTC by trentmwillis

For the case of lazy loading Engines, all QPs get serialized into the URL initially. `undefined` shouldn't get serialized to a string, so that when it gets pulled out the value is not a string.

cc @nathanhammond

2016-10-27 22:27 UTC, nathanhammond commented
People willing to make hard decisions: can we take this a step further? I'd like to force all values passed into `queryParams` to be JSON serializable.

```javascript
 _serializeQueryParams(handlerInfos, queryParams) {
  queryParams = JSON.parse(JSON.serialize(queryParams));
  // ...
```

This makes it possible for people to either pass arbitrary objects which implement `toJSON` as values to keys and also sets us up well for a world in which we do structure query params.

It also neatly sidesteps this issue:

```javascript
JSON.parse(JSON.stringify({foo:undefined}));
// => {}
JSON.parse(JSON.stringify({foo:null}));
// => { foo: null }
```

Thoughts?

2016-10-28 00:21 UTC, rwjblue requested changes
Looks good to me, with one small nit-pick...

2016-10-28 00:21 UTC, rwjblue commented on packages/ember-routing/lib/system/router.js
> +      } else if (value !== undefined) {
Super not-picky but I'd rather leave this as an unconditional else clause. Could you swap this to check if it's undefined and just noop (as an else if before the final else)?

2016-10-28 00:23 UTC, rwjblue commented
@nathanhammond - Let's keep that separate from this PR, but generally I think it could work (generally speaking). Happy to review a PR (or general sketch of the logic).

2016-10-28 01:42 UTC, trentmwillis commented
@rwjblue updated, but getting a linting error. Should I just return from the block?

2016-10-28 16:37 UTC, rwjblue approved these changes

2016-10-28 16:37 UTC, merged

2016-10-28 16:37 UTC, rwjblue commented
Thanks @trentmwillis!