[BUGFIX beta] Make substates great again!
emberjs/ember.js pull request #14545
Opened 2016-10-28 23:28 UTC by trentmwillis

This PR is a pretty substantial overhaul of the internals for how we handle loading/error substates and routes. This makes it much easier (IMO) to follow what is going on internally.

It also fixes issues with Engines, such as https://github.com/dgeb/ember-engines/issues/193. To verify, it introduces a slew of new tests and removes some old ones that weren't testing the behavior we actually wanted.

2016-10-29 21:43 UTC, rwjblue requested changes
Can you update the various rejects to all reject with a value (preferably with an Error), and add expect counts to the new tests?

I'll try do another pass of review tomorrow or Monday, but this is looking very good. Thank you!

2016-10-29 21:43 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/application/engine-test.js
> +          return RSVP.reject();
Can you reject with an Error and display that errors message in the template??

2016-10-29 21:43 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/application/engine-test.js
> +          return RSVP.reject();
Same as above (reject with an error + show error message in template)

2016-10-29 21:43 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/application/engine-test.js
> +          return RSVP.reject();
Same as above (reject with an error + show error message in template)

2016-10-29 21:43 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/application/engine-test.js
> +          return RSVP.reject();
Same as above (reject with an error + show error message in template)

2016-10-29 22:27 UTC, trentmwillis commented
@rwjblue addressed your comments and moved the tests to a more logical spot in that file.

2016-10-29 22:45 UTC, trentmwillis commented
Also added some tests in ember-engines that pass after introducing the changes in this PR: https://github.com/dgeb/ember-engines/pull/247

2016-10-30 00:54 UTC, rwjblue approved these changes

2016-10-30 00:54 UTC, merged

2016-10-30 00:54 UTC, rwjblue commented
Awesome, thank you!

2016-10-30 04:24 UTC, trentmwillis commented
@rwjblue any chance this could get cherry picked into beta?

2016-10-30 12:54 UTC, rwjblue commented
Yep, done!  (was on mobile when I merged originally)

2016-10-30 18:37 UTC, trentmwillis commented
Thanks!