improve doc for filter CP
emberjs/ember.js pull request #14605
Opened 2016-11-14 14:19 UTC by Leooo

Was really not obvious to me before that the `dependentKey` for a `filter` CP could be anything different than the array used to filter.

2016-11-14 15:14 UTC, rwjblue requested changes
Maybe we can give both examples? I think the example that exists now is probably the more common scenario so we should just give both...

2016-11-14 15:43 UTC, Leooo commented
@rwjblue amended

2016-11-14 15:45 UTC, locks commented on packages/ember-runtime/lib/computed/reduce_computed_macros.js
> +  You can also use `@each` in your dependent key, the callback will still use the underlying array:
🤔  I'm a bit concerned people will hurriedly read and start using `chores.@each` (for example) without the leaf property. Maybe `@each.property`? Maybe it's not a concern.

2016-11-14 15:48 UTC, Leooo commented
@locks right, amended

2016-11-14 16:07 UTC, rwjblue commented on packages/ember-runtime/lib/computed/reduce_computed_macros.js
> +  You can also use `@each` in your dependent key, the callback will still use the underlying array:
@locks - FYI `chores.@each` works properly without deprecation as of https://github.com/emberjs/ember.js/pull/12848 (landed in 2.5.0).

2016-11-18 19:10 UTC, pixelhandler commented on packages/ember-runtime/lib/computed/reduce_computed_macros.js
> +  hamster.set('done', false);
What is this setting? should the example be to set the last item of `chores` as `done: false`? or perhaps just remove the `set` example and define one of the chores to have `done: false` in the call to `Hamster.create`

2016-12-08 10:16 UTC, locks commented
@Leooo hi, if you need help addressing @pixelhandler's comments let us know! Let's get this merged :D

2016-12-08 11:47 UTC, Leooo commented
didn't see @locks comment, on it thanks

2016-12-08 12:12 UTC, Leooo commented
@locks @pixelhandler better? I tested the last example, thanks for spotting the issue

2016-12-09 10:00 UTC, locks commented
@Leooo thank you for your work! :) Can you squash the commits for us, and I'll get rwjblue to re-review your PR?

2016-12-09 10:20 UTC, Leooo commented
@locks @rwjblue done thanks

2017-02-24 00:54 UTC, locks approved these changes

2017-02-24 13:51 UTC, rwjblue approved these changes

2017-02-24 13:51 UTC, merged

2017-02-24 13:51 UTC, rwjblue commented
Thank you!