Code cleanup based on ESLint warnings
emberjs/ember.js pull request #14603
Opened 2016-11-11 21:02 UTC by Turbo87

The contents in this PR were mostly extracted from #13549

/cc @rwjblue @stefanpenner

2016-11-11 21:37 UTC, rwjblue requested changes
Looks good, happy to land independently.

Can you fixup the two issues that JSCS caught, and squash the commits?

2016-11-11 21:37 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/components/curly-components-test.js
>          classNames: ['foo', 'bar'],
Need to remove this trailing comma

2016-11-11 21:37 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/components/curly-components-test.js
>          blahzz: ['blark', 'pory'],
trailing comma

2016-11-11 21:42 UTC, Turbo87 commented
@rwjblue done

2016-11-11 22:04 UTC, Turbo87 commented
also fixed the failing JSHint test now... Travis will hopefully agree :)

2016-11-11 22:38 UTC, Turbo87 commented
🍏

2016-11-11 23:21 UTC, rwjblue approved these changes

2016-11-11 23:21 UTC, rwjblue commented
Still need to squash commmits though

2016-11-11 23:23 UTC, Turbo87 commented
@rwjblue not a fan of squashing in general, but: done!

2016-11-12 00:24 UTC, merged

2016-11-12 00:24 UTC, rwjblue commented
Thanks!