ember-testing/setup_for_testing: Use Ember.Test.Adapter if QUnit is unavailable
emberjs/ember.js pull request #14629
Opened 2016-11-22 16:46 UTC by Turbo87

Resolves #14628 

/cc @rwjblue @trentmwillis

2016-11-22 16:59 UTC, rwjblue requested changes

2016-11-22 16:59 UTC, rwjblue commented on packages/ember-testing/lib/setup_for_testing.js
> +    setAdapter((typeof self.QUnit === 'undefined') ? new Adapter() : new QUnitAdapter());
Can you move this logic into a new module (I'd suggest `./adapters/default`)? Then we can simply do:

```js
import DefaultAdapter from './adapter/default';
//..snip...
setAdapter(new DefaultAdapter());
```

2016-11-22 16:59 UTC, rwjblue commented on packages/ember-testing/tests/adapters_test.js
> +  var originalQUnit = window.QUnit;
Please stash this in a module scoped var in the module `setup` above.

2016-11-22 16:59 UTC, rwjblue commented on packages/ember-testing/tests/adapters_test.js
> +  window.QUnit = originalQUnit;
Please reset this in the modules `teardown` above.  We need to ensure that this test failing does not completely hose all the rest of the tests by not cleaning up after itself properly.

2016-11-22 17:12 UTC, Turbo87 commented on packages/ember-testing/lib/setup_for_testing.js
> +    setAdapter((typeof self.QUnit === 'undefined') ? new Adapter() : new QUnitAdapter());
hmm, I'm not sure how that would work. In the current state it checks the `QUnit` global at the time of the `setAdapter()` call, but if we put it inside a separate module we would have to do something like `export default (hasQUnit ? QUnitAdapter : Adapter);` and move the check to boot-time, which makes it harder to test.

2016-11-22 17:12 UTC, Turbo87 commented on packages/ember-testing/tests/adapters_test.js
> +  var originalQUnit = window.QUnit;
👍 

not familiar with QUnit... 😉

2016-11-23 10:02 UTC, Turbo87 commented on packages/ember-testing/tests/adapters_test.js
> +  var originalQUnit = window.QUnit;
@rwjblue done!

2016-11-23 11:53 UTC, merged