[BUGFIX release] this.$() undefined in willDestroyElement hook
emberjs/ember.js pull request #14685
Opened 2016-12-06 18:22 UTC by canufeel

Trying to access `this.$()` in `willDestroyElement` now returns `undefined` as `willDestroyElement` hook is run after the component enters the `destroying` state since 3dcde0f was merged (2.9.0-beta.1). In versions before that `willDestroyElement` was called before transitioning to `destroying` state so the component was using `inDom` state object that would process `this.$()` properly.

Technically the element is still accessible but we have to use `$(this.element)` instead of `this.$()` which makes upgrading cumbersome as it is breaking apps that utilise `willDestroyElement` to deregister eventHandlers previously registered on component element.

2016-12-07 00:38 UTC, krisselden requested changes
looks good to me otherwise

2016-12-07 00:38 UTC, krisselden commented on packages/ember-views/lib/views/states/destroying.js
> +  $(view, sel) {
lets just move it out of states and just make this the method

2016-12-09 06:54 UTC, canufeel commented on packages/ember-views/lib/views/states/destroying.js
> +  $(view, sel) {
@krisselden Thanks for review! View mixin seems to be the most appropriate place for that method. PR updated.

2016-12-14 06:18 UTC, merged

2016-12-14 06:18 UTC, chancancode commented
@canufeel Thank you!

2016-12-15 20:17 UTC, hemp commented
With the context of #14666, thoughts on if this be worthy of cherry-picking back to 2.10.x since it introduced unexpected behavior during an upgrade from 2.9 to 2.10?  

Otherwise I think we might end up waiting to upgrade from 2.9 until 2.11 stable is cut (which is no problem).

2016-12-15 20:28 UTC, chancancode commented
Yes I'll do the cherry pick and release it next week!

2016-12-15 21:47 UTC, hemp commented
Ok, awesome! 🎉

2016-12-19 17:53 UTC, wagenet commented
@chancancode this is hitting our own app 😄

2016-12-19 23:25 UTC, chancancode commented
@hemp @canufeel @wagenet this is released in 2.10.2, thanks again for working on this!