[wip] better backtracking re-render assertion
emberjs/ember.js pull request #14723
Opened 2016-12-15 20:40 UTC by GavinJoyce

Issue: https://github.com/emberjs/ember.js/issues/14709

TODO:

 * [ ] code TODOs
 * [ ] tests

2016-12-17 15:57 UTC, GavinJoyce commented on packages/ember-metal/lib/meta.js
> +  members.lastRenderedTemplateMap = ownMap; // FIXME: not used in production, remove me from prod builds
`runInDebug` doesn't seem to work here. I'd be grateful for any tips on how I can avoid setting these in production build

2016-12-17 17:32 UTC, GavinJoyce commented
this is ready for review (/cc @chancancode)

2016-12-18 01:08 UTC, chancancode commented
Looks great! 👍

I think there are some issues with the meta-metaprogramming usage. For example I believe the underscore was correct, and we could try to figure out the runInDebug stuff. I am currently travelling but I'm sure someone else (Robert, Kris, Edward, Stef etc) could help with those.

Another thing is we probably should be pushing something in all component managers (dynamic components, render helper, mount, etc) as those are all the places we switch templates. 

I think we can improve the message a bit too. Maybe start with the problem summary (you modified X twice in the same render) then go into the details on the next sentence/line to make it more readable.

Other than those, this looks great!! Thanks for working on this.

Can you get some other commenters on the original thread (Stanley?) to try this out?

2016-12-18 09:17 UTC, GavinJoyce commented
> I think we can improve the message a bit too. Maybe start with the problem summary (you modified X twice in the same render) then go into the details on the next sentence/line to make it more readable.

**updated message:**

You modified `message.message_goal.description` twice on `<(subclass of Ember.Model):ember3486>` in a single render. It was rendered in `component:message-edit-expanding-container-component` and then modified in `component:rules/predicate-date-value-component`. This was unreliable and slow in Ember 1.x and is no longer supported. See #13948 for more details.

2016-12-18 13:12 UTC, GavinJoyce commented
I've cut a build and invited people to try it out in their apps: https://github.com/emberjs/ember.js/issues/13948#issuecomment-267820392

2016-12-19 17:25 UTC, scottmessinger commented
@GavinJoyce I love the error message. The "rendered in" and "modified in" parts will be super helpful.

2016-12-23 20:06 UTC, GavinJoyce commented
This is ready for review (/cc @chancancode).

Here's a collection of improved backtracking re-render errors : https://github.com/GavinJoyce/backtracking/pull/10

2017-01-03 09:58 UTC, GavinJoyce commented
I just noticed an issue in my own app, the debug stack seems to be missing a `pop` somewhere:

<img width="486" alt="screen shot 2017-01-03 at 09 56 21" src="https://cloud.githubusercontent.com/assets/2526/21604441/14f51edc-d19b-11e6-8df2-6741298423f1.png">

I'll track down the issue and write a test

2017-01-05 11:55 UTC, GavinJoyce commented
^ That's been addresses. This is ready for review again

2017-01-05 20:54 UTC, rwjblue commented
I think this is good to go, would love for a review by @wycats / @chancancode / @krisselden / @chadhietala for sanity check...

2017-01-06 17:13 UTC, rwjblue requested changes
This looks great! @tomdale and I did a "pair review" session to review this, and came up with a few small tweaks/suggestions.

I think after those are taken care of this is ready to 🚢...

2017-01-06 17:32 UTC, GavinJoyce commented
@rwjblue @tomdale thanks for the great feedback, I'll make the suggested changes soon

2017-01-06 20:32 UTC, tomdale approved these changes

2017-01-06 20:57 UTC, GavinJoyce commented on packages/ember-glimmer/lib/syntax/outlet.js
> +  OutletComponentManager.prototype._pushToDebugStack = function(definition, environment) {
Thanks, I'll follow up in a subsequent PR and refactor away the duplicate `_pushToDebugStack`s

2017-01-06 21:41 UTC, GavinJoyce commented
@rwjblue this is ready to go now I believe

2017-01-06 23:06 UTC, rwjblue approved these changes
Awesome, thank you so much for working on this @gavinjoyce!

2017-01-06 23:06 UTC, merged