[BUGFIX beta] Make `lazyGet` check cache correctly
emberjs/ember.js pull request #14733
Opened 2016-12-18 19:12 UTC by robbiepitts

Fixes #14686

2017-01-04 07:27 UTC, krisselden requested changes
The test needs to be updated so it reflects a realistic scenario.  `UNDEFINED` isn't going to be the direct value of a CP.

2017-01-04 07:27 UTC, krisselden commented on packages/ember-metal/tests/chains_test.js
> +  defineProperty(obj, 'foo', computed(function() { return UNDEFINED; }));
This should return undefined, when it is `undefined` the cache will have `UNDEFINED` and the chain will descend when it should stop.

2017-01-04 18:35 UTC, robbiepitts commented
@krisselden Just pushed your requested changes.

2017-01-05 21:31 UTC, krisselden approved these changes

2017-01-05 21:33 UTC, merged