[DOCS] Tweak addObserver function signature examples
emberjs/ember.js pull request #14804
Opened 2017-01-09 21:00 UTC by knownasilya

The semicolons would have been invalid JS. I also converted to ES2015 while I was here, let me know if that's fine.

2017-01-10 00:25 UTC, locks requested changes
Thanks for spotting this.
Can you improve it a bit more since you're in there?

2017-01-10 00:25 UTC, locks commented on packages/ember-runtime/lib/mixins/observable.js
> -    fooDidChange: function(sender, key, value, rev) { };
Can you wrap the examples in an object? I'm guessing this minimal code sample might be confusing.

2017-01-10 00:46 UTC, knownasilya commented on packages/ember-runtime/lib/mixins/observable.js
> -    fooDidChange: function(sender, key, value, rev) { };
should i add an example like

```js
export default Ember.Component.extend({
  init() {
    this._super(...arguments);
    this.addObserver('someProperty', this, 'aFunc');
  },

  aFunc(sender, key, value, rev) {
    // your code
  }
});
```

2017-01-11 14:18 UTC, rwjblue commented on packages/ember-runtime/lib/mixins/observable.js
> -    fooDidChange: function(sender, key, value, rev) { };
@knownasilya - Yes, that looks much better to me...

2017-01-12 15:13 UTC, locks approved these changes

2017-01-12 15:13 UTC, locks commented
Thank you very much!

2017-01-12 15:14 UTC, merged