Code refactoring for ember-application package
emberjs/ember.js pull request #14823
Opened 2017-01-12 14:24 UTC by artemgurzhii

2017-01-12 14:39 UTC, locks requested changes

2017-01-12 14:39 UTC, locks commented on packages/ember-application/lib/initializers/dom-templates.js
> +let bootstrap = () => { };
can you revert this one please?

2017-01-12 16:49 UTC, locks approved these changes

2017-01-17 00:59 UTC, merged

2017-01-17 00:59 UTC, stefanpenner commented
🎉  👍