add test verifying that registering an unknown service raises an exception
emberjs/ember.js pull request #14850
Opened 2017-01-18 20:39 UTC by GavinJoyce

This now passes, but didn't in Ember 2.10. I git bisected the test and it passes since https://github.com/emberjs/ember.js/pull/14360

2017-01-18 20:58 UTC, rwjblue requested changes

2017-01-18 20:58 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/components/curly-components-test.js
> +    throws(() => {
Should use `expectAssertion` here (otherwise it will fail for prod builds).

2017-01-18 21:01 UTC, GavinJoyce commented on packages/ember-glimmer/tests/integration/components/curly-components-test.js
> +    throws(() => {
apparently not: https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/container/lib/registry.js#L712

Should this be an assertion?

2017-01-18 21:15 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/components/curly-components-test.js
> +    throws(() => {
That `validateInjections` method is only called from here: 
https://github.com/emberjs/ember.js/blob/9b3d581e9b706ae636691b1fff199a86c793b53d/packages/container/lib/container.js#L505-L513

Which is inside of a `runInDebug`...

2017-01-18 21:16 UTC, GavinJoyce commented on packages/ember-glimmer/tests/integration/components/curly-components-test.js
> +    throws(() => {
ah, thanks

2017-01-18 21:29 UTC, GavinJoyce commented on packages/ember-glimmer/tests/integration/components/curly-components-test.js
> +    throws(() => {
It's also called from here, which doesn't seem to be wrapped in a `runInDebug`:

https://github.com/emberjs/ember.js/blob/9b3d581e9b706ae636691b1fff199a86c793b53d/packages/container/lib/container.js#L408

2017-01-18 21:42 UTC, GavinJoyce commented on packages/ember-glimmer/tests/integration/components/curly-components-test.js
> +    throws(() => {
I'm going to wrap the `validateInjections` in a `runInDebug` and change the `Error` to an assert

2017-01-18 22:16 UTC, GavinJoyce commented
@rwjblue I believe that this is ready to go (I think the failing CI is just sauce labs flakiness).

I've wrapped a `container.registry.validateInjections(injections)` in a `runInDebug` so we get a bonus performance improvement

2017-01-18 22:27 UTC, rwjblue approved these changes
LGTM, I restarted the sauce labs job.

2017-01-18 22:42 UTC, GavinJoyce commented
It's 🍏, thanks

2017-01-18 22:54 UTC, merged

2017-03-02 21:51 UTC, spruce commented
Hey,
I just ran into this problem with my addon ember-rapid-forms. Where it is possible to to use i18n but not a requirement. But with this change it fails the tests. Is there a way to walk around this issue. Maybe even a better way to support it. I have no better idea. Could you help? See here: https://travis-ci.org/piceaTech/ember-rapid-forms/jobs/207164170#L593

2017-03-02 22:12 UTC, GavinJoyce commented
@spruce this should help you: https://github.com/RSSchermer/ember-multiselect-checkboxes/pull/41

2017-03-02 22:16 UTC, rwjblue commented
https://github.com/piceaTech/ember-rapid-forms/pull/153