Run backtracking assertion only in debug mode
emberjs/ember.js pull request #14856
Opened 2017-01-20 21:20 UTC by elwayman02

This wraps the `assertNotRendered` check in `runInDebug` so that it won't execute in production, even when either of the flags are enabled.

2017-01-20 21:22 UTC, GavinJoyce commented on packages/ember-metal/lib/property_events.js
> +    runInDebug(() => { assertNotRendered(obj, keyName, meta) });
perhaps move the `runInDebug` to wrap the `if` statement too?

2017-01-20 21:37 UTC, elwayman02 commented on packages/ember-metal/lib/property_events.js
> +    runInDebug(() => { assertNotRendered(obj, keyName, meta) });
Seems reasonable

2017-01-21 01:26 UTC, locks approved these changes

2017-01-23 14:00 UTC, Turbo87 approved these changes

2017-01-25 19:04 UTC, rwjblue requested changes

2017-01-25 19:04 UTC, rwjblue commented on packages/ember-metal/lib/property_events.js
> +      assertNotRendered(obj, keyName, meta)
So I dug into this a bit, and it turns out that this isn't the right fix. Specifically, in the case where `ember-glimmer-allow-backtracking-rerender` is enabled we have to actually call `assertNotRendered` or we will not trigger a rerender when we hit this backtracking.  In other words, wrapping this in `runInDebug` does avoid an error (due to a bug in `assertNotRendered`) but it also breaks the ability for rerendering to happen.


I submitted https://github.com/emberjs/ember.js/pull/14876 to address.

2017-01-25 19:05 UTC, rwjblue commented
I'm going to close this in favor of the refactoring in https://github.com/emberjs/ember.js/pull/14876.  Thank you for pointing out the issue and taking a stab at fixing!

2017-01-25 19:05 UTC, closed without merging

2017-01-25 20:05 UTC, vvohra commented
@rwjblue we're trying to fix the issue in this ticket for 2.10.2. I see that your PR is against master and includes some other refactorings. It's hard to figure out if there's a simpler fix to get this working in 2.10.2.

2017-01-25 20:07 UTC, rwjblue commented
Its likely that my commit in https://github.com/emberjs/ember.js/pull/14876 applies cleanly to release-2-10 branch.

2017-01-25 20:17 UTC, vvohra commented
You're probably right, let me try it once more and run through tests.