[BUGFIX beta] Remove mainContext from global.js fix #14859
emberjs/ember.js pull request #14860
Opened 2017-01-21 13:25 UTC by zoltan-nz

2017-01-21 14:36 UTC, rwjblue requested changes
Thanks for working on this! We need to bring back the line that was removed in the loader. If you can update then I'm happy to land this...

2017-01-21 14:36 UTC, rwjblue commented on packages/ember-environment/lib/global.js
> -               mainContext || // set before strict mode in Ember loader/wrapper
Can you bring this back, and add it back to the correct location in `loader.js`? The ESLint cleanup PR should not have removed it (and I missed that it did when I reviewed).

2017-01-21 15:49 UTC, Turbo87 commented on packages/ember-environment/lib/global.js
> -               mainContext || // set before strict mode in Ember loader/wrapper
Sorry about that. Can we add a comment to it this time describing what the unused variable does?

2017-01-21 16:26 UTC, andyhot commented on packages/ember-environment/lib/global.js
> -               mainContext || // set before strict mode in Ember loader/wrapper
And also add a `// eslint-disable-next-line no-unused-vars` line before the mainContext definition in packages/loader/lib/index.js (even though no-unused-vars is globally off for now)

Still, i'm a bit puzzled by the global.js code... If mainContext is defined nowhere, the code will still fail. And if it is, the next line `new Function('return this')()` will never run. 

Would it make sense to replace `mainContext` with `(typeof mainContext === 'object' && mainContext)` ?

2017-01-21 23:36 UTC, zoltan-nz commented
@rwjblue @Turbo87 `mainContext` added back to the loader with a tiny comment.

2017-01-22 00:25 UTC, merged

2017-01-22 00:26 UTC, rwjblue commented
Thank you!