Phase 3 of public Router Service - adding urlFor
emberjs/ember.js pull request #14979
Opened 2017-03-03 03:50 UTC by scalvert

This PR represents the second phase of the public router service described in [this RFC](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md).

It extends the API with:

- `urlFor`

**Status**: Work in progress

**Reviewers**: @locks @rwjblue @ef4

Changes:

- Added `urlFor` method in public router service
- Added tests

**How to test drive this PR**:

yarn start
Open up 2 tabs pointing to http://localhost:4200/tests/index.html, one with Enable Opt Features checked, ensure tests pass

2017-03-03 04:38 UTC, chadhietala commented
Looking good. What is left? More tests? Really excited about this!

2017-03-03 06:02 UTC, stefanpenner approved these changes

2017-03-03 14:34 UTC, rwjblue requested changes
Looking good!

I think we need test cases for the following scenarios:

* `router.urlFor('something', { selectedItems: ['a', 'b', 'c'] })` (a query param that is an array)
* `router.urlFor('something', { stuff: null })`
* `router.urlFor('something', { stuff: undefined })`
* `router.urlFor('something', { stuff: 'foo' })` where `something` route defines a custom `serializeQueryParam` method
* Tests defining a controller for the target, where the controller throws an error in `init`. The idea here is to ensure that we are not forcing controller instances to be created when generating the URL (which is a significant part of the performance issues surrounding `{{link-to}}`).

2017-03-03 14:34 UTC, rwjblue commented on packages/ember-routing/lib/system/router.js
> +    let url = this._routerMicrolib.generate(...args);
Why do we need this change?  As you can see [here](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&code=let%20obj%20%3D%20%7B%0A%20%20generate(...args)%20%7B%0A%20%20%20%20let%20url%20%3D%20this._routerMicrolib.generate(...args)%3B%0A%20%20%20%20return%20this.location.formatURL(url)%3B%0A%20%20%7D%0A%7D%0A%0Alet%20obj2%20%3D%20%7B%0A%20%20generate()%20%7B%0A%20%20%20%20let%20url%20%3D%20this._routerMicrolib.generate(...arguments)%3B%0A%20%20%20%20return%20this.location.formatURL(url)%3B%0A%20%20%7D%0A%7D) the transpiled output is the same before and after.

Seems fine to make the change, but I was just curious what motivated it...

2017-03-03 14:34 UTC, rwjblue commented on packages/ember/tests/routing/router_service_test/urlFor_test.js
> +    constructor() {
This `constructor` isn't really needed here, can remove..

2017-03-03 14:34 UTC, rwjblue commented on packages/ember-routing/lib/services/router.js
> +     @param {Object} [options] optional hash with a queryParams property
The RFC suggests that the argument signature for `urlFor` is `routeName, ...models, queryParams`, however this is proposing `routeName, ...models, { queryParams }` (destructuring `queryParams` off of the last "options" argument).  See [RFC details here](https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#new-method-url-generation).  

Why are we diverging?  Did you discover something during implementation that suggests we should have these diverge from the RFC (and no longer have the same API as `transitionTo` and `replaceWith`)?

2017-03-03 15:13 UTC, rwjblue commented
> Tests defining a controller for the target, where the controller throws an error in init. The idea here is to ensure that we are not forcing controller instances to be created when generating the URL (which is a significant part of the performance issues surrounding {{link-to}}).

This [JSBin Demo](https://jsbin.com/tusekuc/edit?html,js,output) demonstrates that a bit more work will be needed to satisfy this constraint. 

Currently, when `routerMicrolib` invokes its `getHandler` function ([defined here](https://github.com/emberjs/ember.js/blob/a82158362cf4c4ce1447cefae3f8445ff37a9f46/packages/ember-routing/lib/system/router.js#L577-L619)), we look up the route, then eagerly invoke `route._populateQPMeta()` ([here](https://github.com/emberjs/ember.js/blob/a82158362cf4c4ce1447cefae3f8445ff37a9f46/packages/ember-routing/lib/system/router.js#L612)).

2017-03-03 15:53 UTC, rwjblue commented
> Currently, when `routerMicrolib` invokes its `getHandler` function ([defined here](https://github.com/emberjs/ember.js/blob/a82158362cf4c4ce1447cefae3f8445ff37a9f46/packages/ember-routing/lib/system/router.js#L577-L619)), we look up the route, then eagerly invoke `route._populateQPMeta()` ([here](https://github.com/emberjs/ember.js/blob/a82158362cf4c4ce1447cefae3f8445ff37a9f46/packages/ember-routing/lib/system/router.js#L612)). 

As I was digging into this, I was able to chart a path forward.  Please review https://github.com/emberjs/ember.js/pull/14980, which should resolve the specific entanglement I mentioned above...

2017-03-03 16:57 UTC, scalvert commented
@chadhietala more tests, working out specifics of performance characteristics (@rwjblue already found issues with eager instantiation of controllers), etc.

2017-03-03 16:59 UTC, scalvert commented on packages/ember-routing/lib/system/router.js
> +    let url = this._routerMicrolib.generate(...args);
I added this while I was fiddling with the params to ensure they were passed through to `_routerMicrolib.generate` in the expected format. I realized that this method handles extracting the params correctly already, so this is just a remnant of that. Will revert for sure!

2017-03-03 17:00 UTC, scalvert commented on packages/ember/tests/routing/router_service_test/urlFor_test.js
> +    constructor() {
I had been doing some custom work in this constructor, but removed it. The constructor was just left in place. Will remove!

2017-03-03 17:04 UTC, scalvert commented on packages/ember-routing/lib/services/router.js
> +     @param {Object} [options] optional hash with a queryParams property
My interpretation was that we should mimic the signatures of `transitionTo` and `replaceWith`, as it's preferable to have a consistent API across all public methods. That said, I think what you said here is totally legit, in that the `queryParams` object should *be* the queryParams itself, not an object having a `queryParams` property that is the actual queryParams. 

I'm going to revisit all of them for consistency, but I know that `EmberRouter` expects an object that has a `queryParams` property that it unpacks. If we go this route we may want to revisit how `EmberRouter` is handling extracting the QPs.

Thoughts?

2017-03-03 17:06 UTC, scalvert commented
@rwjblue thanks for all the investigation! I totally appreciate it. 

The controller.init -> error test case was one that we'd discussed before, and is definitely one I want to add. I'm going to start listing all the test cases in a todo in the description of this PR, so we can ensure we're covering all the permutations.

I've reviewed https://github.com/emberjs/ember.js/pull/14980 and dropped a comment on it.

2017-03-03 17:12 UTC, rwjblue commented on packages/ember-routing/lib/services/router.js
> +     @param {Object} [options] optional hash with a queryParams property
Yeah, I think it makes sense to use the same interface as `.transitionTo` / `.replaceWith` (which both have options with a `queryParams` property on them).  We can get @ef4 and others to confirm just before landing, but I think it makes sense to stay consistent for now.

If we do decide to change the API, they should all be changed, which is definitely unrelated to this PR...

2017-03-03 17:19 UTC, scalvert commented on packages/ember-routing/lib/services/router.js
> +     @param {Object} [options] optional hash with a queryParams property
As per the RFC:

> This takes the same arguments as transitionTo

2017-03-03 17:20 UTC, chadhietala commented
Since this is one of the places where we need to improve on performance I think it might be useful to use a spy on methods we know we should not enter or entered a well known amount of time. In the long term we need to get Heimdall instrumentation in here, but I think asserting call counts in the tests can give us some confidence here.

2017-03-03 17:23 UTC, rwjblue commented on packages/ember-routing/lib/services/router.js
> +     @param {Object} [options] optional hash with a queryParams property
HAHA! Derp.  I just was focusing on the code snippet:

```js
urlFor(routeName, ...models, queryParams)
```

Which is actually incorrect, it should have said:

```js
urlFor(routeName, ...models, { queryParams })
```

Or:

```js
urlFor(routeName, ...models, options)
```

(based on the prose just below)

https://github.com/emberjs/rfcs/blob/master/text/0095-router-service.md#new-method-url-generation

2017-03-05 19:46 UTC, scalvert commented
Looks like #14980 correctly resolved `urlFor` causing lookups on controllers. I verified this by adding the getters to the app as per your JSBin, ensuring the tests failed, and subsequently merging in the upstream changes. After the merge the tests now pass.

⭐️

2017-03-06 17:44 UTC, scalvert commented
@rwjblue added more tests for permutations of calls. What's left?

2017-03-07 18:22 UTC, rwjblue reviewed
Additional tests needed:

* generating path via `routerService.urlFor(...stuff...)` then calling `routerService.transitionTo(pathGenerated)` ends up on the same path as `urlFor` generated
  * no dynamic segments (models) or query params
  * with dynamic segments (models) no query params
  * no dynamic segments (models) with query params
  * with dynamic segments (models) and query params
* Still need tests for paths generated for routes including a custom `serializeQueryParam`

2017-03-08 01:43 UTC, scalvert commented
Good ideas on the tests! Will work on adding those. 

The last one where we're testing paths generated for routes including a custom `serializeQueryParam` - shouldn't we wait until we fix the QP serialization, which we discussed would be a fast follow of this work?

2017-03-08 01:45 UTC, rwjblue commented
Yep, sounds good! Also, those `serializeQueryParam` tests and implementation work can close https://github.com/emberjs/ember.js/issues/11288.

2017-03-08 12:28 UTC, rwjblue approved these changes

2017-03-08 12:28 UTC, merged

2017-03-08 12:29 UTC, rwjblue commented
Thank you @scalvert!