ember-views cleanup
emberjs/ember.js pull request #15019
Opened 2017-03-15 15:12 UTC by artemgurzhii

2017-03-15 15:42 UTC, stefanpenner approved these changes

2017-03-15 15:42 UTC, stefanpenner commented on packages/ember-views/lib/system/event_dispatcher.js
>      rootElement.on(`${event}.ember`, '.ember-view', function(evt, triggeringManager) {
should we instead use `=>` that way `this` is preserved behind the scenes.

2017-03-15 15:43 UTC, stefanpenner requested changes

2017-03-15 15:43 UTC, stefanpenner commented on packages/ember-views/lib/views/core_view.js
> +      let args = [...arguments];
this seems to result in 

```
var args = [].concat(Array.prototype.slice.call(arguments));
```

The existing code is going to be more efficient

2017-03-15 16:05 UTC, artemgurzhii commented on packages/ember-views/lib/system/event_dispatcher.js
>      rootElement.on(`${event}.ember`, '.ember-view', function(evt, triggeringManager) {
Wouldn't work because of [this](https://github.com/emberjs/ember.js/pull/15019/files#diff-c7b9de937661f47b233bb5e3101436e0R206).

2017-03-16 08:16 UTC, artemgurzhii commented on packages/ember-views/lib/views/core_view.js
> +      let args = [...arguments];
Done!

2017-03-16 10:11 UTC, chancancode commented on packages/ember-views/lib/mixins/action_support.js
> +      if (shouldBubble === false) { return; }
The before/after does not do the same thing.

2017-03-16 10:13 UTC, artemgurzhii commented on packages/ember-views/lib/mixins/action_support.js
> +      if (shouldBubble === false) { return; }
Why?

2017-03-16 10:36 UTC, chancancode commented on packages/ember-views/lib/mixins/action_support.js
> +      if (shouldBubble === false) { return; }
Before it was checking that the return value is exactly true, now it is checking that the return value is exactly false; if the function returns anything other than true or false, including returning nothing (undefined), the behavior is different

2017-03-16 11:52 UTC, artemgurzhii commented on packages/ember-views/lib/mixins/action_support.js
> +      if (shouldBubble === false) { return; }
Done!

2017-03-27 23:41 UTC, homu commented
:umbrella: The latest upstream changes (presumably #15077) made this pull request unmergeable. Please resolve the merge conflicts.

2017-05-21 00:56 UTC, homu commented
:umbrella: The latest upstream changes (presumably #15262) made this pull request unmergeable. Please resolve the merge conflicts.

2017-08-31 20:59 UTC, closed without merging