Allow mounting routeless engines with a bound engine name
emberjs/ember.js pull request #15015
Opened 2017-03-14 22:16 UTC by mike183

This PR builds upon the work in #14967, introducing the ability to pass bound properties to the `{{mount}}` syntax, enabling the dynamic mounting of "routeless" engines.

This also resolves ember-engines/ember-engines#117

cc/ @rwjblue

2017-03-14 22:26 UTC, rwjblue commented
LGTM

@dgeb / @chancancode / @trentmwillis - Any objections?

2017-03-14 23:53 UTC, trentmwillis requested changes
Overall, I'm good with it. For bad input though, I'd like to see feedback given to the user.

2017-03-14 23:53 UTC, trentmwillis commented on packages/ember-glimmer/lib/syntax/mount.js
> +      return null;
IMO this should log if the argument isn't a `string/undefined/null`.

2017-03-15 00:10 UTC, rwjblue commented on packages/ember-glimmer/lib/syntax/mount.js
> +      return null;
ya, lets have it assert

2017-03-18 12:26 UTC, mike183 commented
@trentmwillis Thanks for the review, I've added an assertion to check that the provided engine name is valid and also added a test to go along with it.

cc/ @rwjblue

2017-03-18 15:53 UTC, rwjblue approved these changes

2017-03-18 15:53 UTC, merged

2017-03-18 15:56 UTC, mike183 commented
🎉