[DOC] update missing yield docs in api #14797
emberjs/ember.js pull request #15083
Opened 2017-03-27 21:27 UTC by mattmarcum

For (14979)[https://github.com/emberjs/ember.js/issues/14797]

Just getting the ball running on these missing docs.  These are copied over from the old docs that were removed, with the section on Ember.View removed.  Let me know if you want anymore changes.

2017-03-27 23:42 UTC, mmun commented
This looks great. Would you be able change the example to yield an argument? or add an additional example?

Additionally, we should probably pull this into the release channel. Does that sound good @rwjblue?

2017-03-28 06:14 UTC, mattmarcum commented
Ok, I gave it a go

2017-03-28 12:11 UTC, locks requested changes
Some whitespace and code block tweaks necessary.

2017-03-28 12:11 UTC, locks commented on packages/ember-glimmer/lib/index.js
> +  When designing components `{{yield}}` is used to denote where, inside the component's
add empty new line between the header and the text please

2017-03-28 12:11 UTC, locks commented on packages/ember-glimmer/lib/index.js
> +  ```handlebars
empty lines around the code block please:

    should render:

    ```handlebars
    ...
    ```

    ```handlebars
    …
    ```

2017-03-28 12:11 UTC, locks commented on packages/ember-glimmer/lib/index.js
> +  ```handlebars
same whitespace here

2017-03-28 12:11 UTC, locks commented on packages/ember-glimmer/lib/index.js
> +  ```handlebars
you can also do

    ```app/application.hbs

instead of the comment, and our system will render a nice header with the path

2017-03-30 00:23 UTC, mixonic commented
@locks there is an update here if you can review, thanks 🙇

2017-03-30 03:13 UTC, locks approved these changes

2017-03-30 03:14 UTC, locks commented
We are good to gooooo, thanks @mattmarcum for sticking the landing :)

2017-03-30 03:14 UTC, merged