Decouple test from the default resolver for data_adapter
emberjs/ember.js pull request #15091
Opened 2017-03-27 23:27 UTC by Gaurav0

For #15058

2017-04-03 16:41 UTC, mixonic requested changes
I believe that first test can just have its description changed. A read of https://github.com/emberjs/ember.js/blob/master/packages/ember-extension-support/lib/data_adapter.js doesn't make me believe these tests are specific to the default resolver, nor do these tests.

Some small cleanup remains. Thanks @Gaurav0!

2017-04-03 16:41 UTC, mixonic commented on packages/ember-extension-support/tests/data_adapter_test.js
> +    let self = this;
I don't believe `self` is used here

2017-04-03 16:41 UTC, mixonic commented on packages/ember-extension-support/tests/data_adapter_test.js
> +  ['@test Model types added with DefaultResolver']() {
So this test is specifically mentioning `DefaultResolver`. By migrating to the `ApplicationTestCase` and using `add` etc, it is no longer using the default resolver. Instead it now uses the TestResolver.

Either the test description is wrong and the data adapter doesn't require the DefaultResolver, or this test should not be ported. I''m not sure which.

2017-04-03 16:41 UTC, mixonic commented on packages/ember-extension-support/tests/data_adapter_test.js
> +    this.set('containerDebugAdapter', {
I don't think this property is used?

2017-04-03 16:41 UTC, mixonic commented on packages/ember-extension-support/tests/data_adapter_test.js
> +import { ModuleBasedResolver } from 'internal-test-helpers/test-resolver';
This import is not used.

2017-04-03 16:56 UTC, Gaurav0 commented on packages/ember-extension-support/tests/data_adapter_test.js
> +    this.set('containerDebugAdapter', {
Tests fail without a mock containerDebugAdapter.

2017-04-03 16:57 UTC, Gaurav0 commented on packages/ember-extension-support/tests/data_adapter_test.js
> +    let self = this;
Fixed.

2017-04-03 16:58 UTC, Gaurav0 commented on packages/ember-extension-support/tests/data_adapter_test.js
> +import { ModuleBasedResolver } from 'internal-test-helpers/test-resolver';
Fixed.

2017-04-03 16:58 UTC, Gaurav0 commented on packages/ember-extension-support/tests/data_adapter_test.js
> +  ['@test Model types added with DefaultResolver']() {
Removing DefaultResolver from description

2017-04-05 14:56 UTC, mixonic commented on packages/ember-extension-support/tests/data_adapter_test.js
> +    this.set('containerDebugAdapter', {
I misread this the first time, looks good 👍

2017-04-05 14:56 UTC, mixonic approved these changes

2017-04-05 14:56 UTC, merged

2017-04-05 14:56 UTC, mixonic commented
Thank you @Gaurav0!