Decouple controller_for test from globals resolver
emberjs/ember.js pull request #15100
Opened 2017-04-01 01:20 UTC by stevenwu

Thanks @mmun for help.

#15058

2017-04-01 04:25 UTC, mmun commented on packages/ember-routing/tests/system/controller_for_test.js
> -  namespace.Controller = Controller.extend();
This line became https://github.com/emberjs/ember.js/pull/15100/files#diff-5251a48efdb95856746f72151cc33bbbR32, but I would have expected the factory be registered as `controller:main` and not `controller:basic`.

2017-04-03 16:46 UTC, mixonic commented on packages/ember-routing/tests/system/controller_for_test.js
> -  namespace.Controller = Controller.extend();
Seems like it is `basic` https://github.com/emberjs/ember.js/blob/ee8ab348484421f254fe995c6f04f0d4a0859cfa/packages/ember-routing/lib/system/generate_controller.js#L19 Works in the resolver b/c `useRouterNaming` is called for controllers https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/resolver.js#L288 barf.

2017-04-03 16:51 UTC, mixonic requested changes
I've requested some very small cleanup but this is pretty close!

2017-04-03 16:51 UTC, mixonic commented on packages/ember-routing/tests/system/controller_for_test.js
> +  ['@test generateController should return App.Controller if provided'](assert) {
Can this test be changed to `should return controller:basic if resolved` instead? The global `App.Controller` has no relevance to the remaining test (and is less informative).

2017-04-03 16:51 UTC, mixonic commented on packages/ember-routing/tests/system/controller_for_test.js
> +  ['@test generateController should return controller:basic if provided'](assert) {
This test was poorly named. It was testing the case of a registered factory. The test above it tests the resolved case.

As such, this test should not use `this.add('controller:basic'` but instead should register the factory:

* `this.application.register('controller:basic'`
* Even more like the old test would be `this.applicationInstance.register('controller:basic'` after the `visit` call.

Finally the test name should be `@test generateController should return controller:basic if registered` (note "registered" vs. "resolved" in the above test).

2017-04-03 17:28 UTC, mmun commented on packages/ember-routing/tests/system/controller_for_test.js
> -  namespace.Controller = Controller.extend();
@mixonic Whoa. Didn't expect that!

2017-04-03 23:16 UTC, stevenwu commented on packages/ember-routing/tests/system/controller_for_test.js
> +    this.application.register('controller:basic', BasicController);
@mixonic I tried `this.applicationInstance.register('controller:basic', BasicController)` after `visit` but the test fails.

2017-04-05 14:58 UTC, mixonic approved these changes

2017-04-05 14:58 UTC, merged

2017-04-05 14:58 UTC, mixonic commented
Excellent, thank you @stevenwu!