Update a test to fail #14843
emberjs/ember.js pull request #15110
Opened 2017-04-05 00:08 UTC by hjdivad

Also illustrate the suggested fix in code.

2017-04-05 01:52 UTC, stefanpenner requested changes
Left some notes, if we decide to proceed.

Would love @krisselden's input

2017-04-05 01:52 UTC, stefanpenner commented on packages/ember-runtime/lib/mixins/array.js
> +        ((startIdx === 0 && (addAmt > 0 || removeAmt > 0)) ||
should we still include `objectAt(array, 0) !== cacheFor.get(cache, 'firstObject')` guard?

2017-04-05 01:52 UTC, stefanpenner commented on packages/ember-runtime/lib/mixins/array.js
> +        (startIdx < 0 && (removeAmt >= -startIdx)))) {
should we still include `objectAt(array, get(array, 'length') - 1) !== cacheFor.get(cache, 'lastObject')) {` guard ?

2017-04-05 01:52 UTC, stefanpenner commented on packages/ember-runtime/lib/mixins/array.js
> +    let length = get(array, 'length') + removeAmt - addAmt;
we should likely avoid this `get` if we are not needing it.

This is getting complicated, if we go down this path we should do a helper function that can be unit tested (and more readable).

2017-04-05 01:52 UTC, stefanpenner commented on packages/ember-runtime/tests/suites/mutable_array/insertAt.js
> +  let objectAt = obj.objectAt;
we will require more test permutations, as the above code has many bounds

2017-04-05 01:55 UTC, hjdivad commented
Three possible courses of action:

1. do nothing
2. check the index ranges before calling `objectAt`
3. remove `objectAt` entirely and only check index ranges

2017-05-06 00:01 UTC, homu commented
:umbrella: The latest upstream changes (presumably #15210) made this pull request unmergeable. Please resolve the merge conflicts.

2017-07-14 03:53 UTC, stefanpenner commented
@bekzod if you happen to have cycles. I think we would like to move forward with this PR, maybe you can lend @hjdivad a hand and help him land it?

2017-07-14 04:37 UTC, bekzod commented
@stefanpenner sure, will look at it

2017-07-14 17:51 UTC, bekzod commented
maybe following code is a bit clearer (tested with new test) ? @stefanpenner @hjdivad 
```
 if (cache !== undefined) {
    if (cache.firstObject !== undefined && startIdx === 0 && objectAt(array, 0) !== cacheFor.get(cache, 'firstObject')) {
      propertyWillChange(array, 'firstObject');
      propertyDidChange(array, 'firstObject');
    }

    if (cache.lastObject !== undefined) {
      let delta = (addAmt === -1 ? 0 : addAmt) - (removeAmt === -1 ? 0 : removeAmt);
      let length = get(array, 'length');

      let lastIndex = length - delta - 1;
      if ((lastIndex === -1 || delta === 0 || !(startIdx < lastIndex && lastIndex < length)) && objectAt(array, length - 1) !== cacheFor.get(cache, 'lastObject')) {
        propertyWillChange(array, 'lastObject');
        propertyDidChange(array, 'lastObject');
      }
   }
  }
```
also can `startIdx` be negative in `arrayContentDidChange`  ?

2017-07-15 04:32 UTC, bekzod commented
I think the approach suggested is good enough, cannot think of better way for now will improve this once merged if I get any better ideas

2017-07-16 00:09 UTC, stefanpenner commented
@bekzod nice, are you able to do the rebase + fix any failing tests? Feel free to open a new PR.

2017-07-17 19:22 UTC, hjdivad commented
Closed in favour of #15510

2017-07-17 19:22 UTC, closed without merging

2017-07-17 19:22 UTC, hjdivad commented
> also can startIdx be negative in arrayContentDidChange ?

Yes, the semantics mirror those of [splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)