[WIP] Ensure using no-double-extend does not modify an object's own keys.
emberjs/ember.js pull request #15164
Opened 2017-04-24 20:47 UTC by rwjblue

Given:

```js
owner.register('some:name', Ember.Object.extend());
let instance = owner.lookup('some:name');

assert.deepEqual(Object.keys(instance), []);
```

This assertion passes in Ember 2.12 and older, but not Ember 2.13.0 beta series. The cause of this regression was disabling `no-double-extend` feature and now some properties like `_debugContainerKey` and `NAME_KEY` are being set on new instances.

2017-04-24 21:05 UTC, krisselden commented on packages/container/lib/container.js
> +  factoryToString() {
why not just make this `toString() {}`

2017-04-24 21:07 UTC, krisselden commented on packages/ember-runtime/lib/system/core_object.js
> +    let factoryToString = this[NAME_KEY] || (factoryManager && factoryManager.factoryToString());
if `factoryToString()` was just toString() you wouldn't need to call it you can just let the string template call it.

2017-04-24 21:53 UTC, krisselden requested changes

2017-04-24 21:53 UTC, krisselden commented on packages/container/lib/container.js
> +      setFactoryManager(factory, this);
factory here doesn't not have a 1 to 1 with FactoryManager, FactoryManager has only one factory but a factory can have multiple managers.

2017-04-25 18:34 UTC, rwjblue commented on packages/container/lib/container.js
> +      setFactoryManager(factory, this);
Yeah, this is a fairly major issue for us. I'll ponder it a bit...

2017-04-27 00:18 UTC, closed without merging