[BUGFIX beta] Always emit the same ember-template-compiler.js (as a debug build).
emberjs/ember.js pull request #15199
Opened 2017-05-02 21:35 UTC by rwjblue

Changing the output of `ember-template-compiler.js` based on `ember b -prod` means that the resulting asset can only be used with `ember.prod.js` (and not with `ember.debug.js`).

This removes the customization and forces all versions of `ember-template-compiler.js` to be in debug mode.

Addresses #15198

2017-05-02 22:06 UTC, chadhietala approved these changes

2017-05-03 10:44 UTC, cibernox requested changes

2017-05-03 10:44 UTC, cibernox commented on ember-cli-build.js
> +    ...templateCompiler(babelDebugHelpersES5),
I believe that the spread operator is behind the harmony flag in node 4: http://node.green/#ES2015-syntax-spread-------operator

2017-05-03 10:55 UTC, rwjblue commented on ember-cli-build.js
> +    ...templateCompiler(babelDebugHelpersES5),
Ya, confirm but we are using node 6 (and have a few other usages of node 6isms).

2017-05-03 11:00 UTC, cibernox commented on ember-cli-build.js
> +    ...templateCompiler(babelDebugHelpersES5),
I asked in case this code is run (or will eventually) but consuming apps. Then, no arguments.

2017-05-03 11:00 UTC, cibernox approved these changes

2017-06-27 21:50 UTC, cibernox commented
@rwjblue what is the status of this?

2019-08-16 16:41 UTC, closed without merging