[BUGFIX beta] property_set should reuse reference to its meta
emberjs/ember.js pull request #15210
Opened 2017-05-05 16:23 UTC by stefanpenner

2017-05-05 16:25 UTC, scalvert commented
Good catch! No peeking :)

2017-05-05 16:35 UTC, krisselden approved these changes

2017-05-05 16:37 UTC, runspired commented on packages/ember-runtime/lib/mixins/array.js
> +      meta = meta || peakMeta(this);
is this a misspelling ?

2017-05-05 16:37 UTC, runspired commented on packages/ember-runtime/lib/mixins/array.js
> +      meta = meta || peakMeta(this);
It is, should be `peekMeta`

2017-05-05 16:38 UTC, runspired commented on packages/ember-runtime/lib/mixins/array.js
> +      meta = meta || peakMeta(this);
although I do like that we've hit "peak meta"

2017-05-05 16:38 UTC, runspired commented on packages/ember-runtime/lib/mixins/array.js
> +      meta = meta || peakMeta(this);
same as above, `peekMeta`

2017-05-05 16:40 UTC, runspired requested changes
Fix da peak

2017-05-05 16:41 UTC, runspired approved these changes

2017-05-05 16:43 UTC, stefanpenner commented
@bmeurer this should eat into the 5% of time spent in weakmap lookup you guys where seeing.

2017-05-05 18:10 UTC, stefanpenner commented
@homu r+

2017-05-05 18:10 UTC, homu commented
:pushpin: Commit a7ab514 has been approved by `stefanpenner`

<!-- @homu r=stefanpenner a7ab514d5cf6c325d85080b055f320bacf5964a9 -->

2017-05-05 18:10 UTC, homu commented
:hourglass: Testing commit a7ab514 with merge 22804ea...

2017-05-05 21:48 UTC, stefanpenner commented
@homu retry

2017-05-05 21:48 UTC, homu commented
:hourglass: Testing commit a7ab514 with merge 4e868e9...

2017-05-05 21:59 UTC, stefanpenner commented
@homu what's taking you so long :(

2017-05-05 23:51 UTC, rwjblue commented
I think homu is basically broken here :(

2017-05-05 23:52 UTC, merged

2017-05-07 12:17 UTC, bmeurer commented
I don't have the full context on this change.

2017-05-07 15:01 UTC, stefanpenner commented
Sorry. This pull request removes repeated and unnecessary `weakmap get`'s... I realize you guys are also working on improving weakmap perf so I figure I would loop you in.

TL;DR this pr reduces the number of WeakMapGets's to at least 1/3 in some cases.

2017-05-08 00:18 UTC, bmeurer commented
Ah I see. That makes total sense, no matter what V8 (or any other engine) is doing.

2017-05-08 16:57 UTC, stefanpenner commented
@bmeurer yup, should work in combination with any work engines do.