expandProperties optimizations
emberjs/ember.js pull request #15219
Opened 2017-05-09 21:18 UTC by SpikedKira

benchmarks: https://jsperf.com/expandproperties/1

2017-05-10 12:35 UTC, rwjblue commented
Would love thoughts from @krisselden  / @stefanpenner.  

Also, pinging @nickiaconis to see if he minds reviewing as well (IIRC he worked on the current implementation).

2017-05-10 15:29 UTC, stefanpenner commented
for the `indexOf` I've noticed a simple loop + charCodeAt is often faster. May be worth trying out (but not a blocker).

```js
function charCodeIndexOf(string, charCode) {
  for (let i = 0; i < string.length; i++) {
     if (string.charCodeAt(i) === charCode) {
       return i;
     }
  }
}
```

2017-05-10 15:36 UTC, stefanpenner commented on packages/ember-metal/lib/expand_properties.js
> +    NESTED_BRACES = /\{[^}{]*\{|\}[^}{]*\}|\{[^}]*$/g;
we should likely in-line this into 46, and leave a comment. That way when the assert is stripped the RegExp is aswell.

2017-05-10 15:36 UTC, stefanpenner commented on packages/ember-metal/lib/expand_properties.js
> +  let start = pattern.indexOf('{');
At least the first time through, this `pattern.indexOf('{` has already been run on 49, could we re-use that result?

2017-05-10 15:37 UTC, stefanpenner commented
> Also, pinging @nickiaconis to see if he minds reviewing as well (IIRC he worked on the current implementation).

Ya it would be great to get @nickiaconis feedback, maybe he has some further ideas.

2017-05-10 15:37 UTC, SpikedKira commented on packages/ember-metal/lib/expand_properties.js
> +    NESTED_BRACES = /\{[^}{]*\{|\}[^}{]*\}|\{[^}]*$/g;
agreed

2017-05-10 15:40 UTC, SpikedKira commented
In regards to the for/indexOf... I tried to walk the line between the optimizations of various browsers.  Chrome has overly optimized indexOf, and while for is faster in Firefox, indexOf in Firefox is still far faster than for-loop in Chrome.  I'm also seeing indexOf optimized over for-loop in Edge. (I'm missing data on Safari)

2017-05-10 15:55 UTC, SpikedKira commented on packages/ember-metal/lib/expand_properties.js
> +  let start = pattern.indexOf('{');
yeah that optimization was for the most likely case of no-expansion.  I did look at re-using once already but I'll look again with some freshly caffeinated eyes :D

2017-05-10 16:00 UTC, stefanpenner commented
@SpikedKira interesting. In my (potentially flawed) tests `indexOf` and `for` + `charCodeAt` suggests the latter.

I would be curious if you could take a look, and ensure I am not trolling myself.

```js
var string = 'foo.{bar,baz}';

require('do-you-even-bench')([
  { name: 'charCodeAt',
    fn: function() {
      for (var i = 0; i < string.length; i ++) {
        if (string.charCodeAt(i) === 123) {
          return i;
        }
      }
      return -1;
    }
  },
  { name: 'indexOf', fn: function() { return string.indexOf('{'); } }
]);


// testing
// - charCodeAt
// - indexOf
// running first test, please wait...
//  charCodeAt ... 48,437,997.64 op/s
//  indexOf ...... 17,884,808.89 op/s

/*
npm version
{ 'perf-scratch': '1.0.0',
  npm: '4.0.5',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.4.0',
  openssl: '1.0.2j',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.10.1',
  v8: '5.4.500.45',
  zlib: '1.2.8' }
*/
```

2017-05-10 16:16 UTC, stefanpenner commented
Ah, it may be turbofan vs crankshaft difference. As the version of node ^ this code-path his cranksaft and doesn't produce nearly as nice code as TF

2017-05-10 16:30 UTC, stefanpenner commented
TL;DR @SpikedKira I think using `indexOf` here is a good future proof thing for us to use. The only downside I could see is that ember currently does extend the string prototype which may cause some optimization sadness. cc @krisselden

2017-05-10 18:07 UTC, SpikedKira commented
@stefanpenner admittedly, had to look some of that up.  Crackshaft explains why I was seeing a much different picture when benchmarking in node vs the browsers.  Would very much welcome info on your benching setup.

2017-05-10 19:07 UTC, stefanpenner commented
@SpikedKira ya, I should write a blog post or something sometime.

> Crackshaft explains why I was seeing a much different picture when benchmarking in node vs the browsers.

I suspect you were seeing better performance in browsers?

2017-05-10 20:01 UTC, SpikedKira commented
@stefanpenner correct, Node was showing unique performance in several loops vs latest browsers

2017-05-10 21:46 UTC, SpikedKira commented
New changes based on feedback from @stefanpenner . Pretty sure I covered them all, I think it extracted a few extra ops/sec.

2017-05-10 22:53 UTC, stefanpenner requested changes
Let one nit-pick, then I am good to :shipit:

2017-05-10 22:53 UTC, stefanpenner commented on packages/ember-metal/lib/expand_properties.js
> +    dive("", pattern, start, callback);
To address my ADD, let's make this single quotes instead of double quotes.

2017-05-11 06:41 UTC, stefanpenner approved these changes

2017-05-11 14:58 UTC, stefanpenner commented
mind squashing, and prefixing the commit message with `[BUGFIX beta]` ? That way we can sneak it in sooner.

2017-05-11 16:26 UTC, merged

2017-05-11 18:32 UTC, rwjblue commented
Thanks @SpikedKira!

2017-05-11 23:45 UTC, nickiaconis commented
I'm late to the party, but this looks good to me. I added a test with my fix, and tests passed with these changes, so all's good. Thanks for the improvement @SpikedKira!