[DOCUMENTATION] Add return types whenever possible to promises
emberjs/ember.js pull request #15316
Opened 2017-06-01 19:01 UTC by Serabe

Addresses #15114 in emberjs/ember.js

2017-06-01 19:55 UTC, stefanpenner requested changes

2017-06-01 19:55 UTC, stefanpenner commented on packages/ember-testing/lib/helpers/wait.js
> +  @return {RSVP.Promise<Object>} Promise that resolves to the passed value.
isn't this `<any>` ?

2017-06-01 23:02 UTC, Serabe commented on packages/ember-testing/lib/helpers/wait.js
> +  @return {RSVP.Promise<Object>} Promise that resolves to the passed value.
I used object because it is the type specified for `value`, changing it.

2017-06-18 17:10 UTC, Serabe commented
I've added the changes. Sorry for the delay, got too many things on my plate :$

2017-06-18 23:58 UTC, locks approved these changes

2017-06-19 01:19 UTC, merged

2017-06-19 01:19 UTC, rwjblue commented
Thank you @Serabe!