Decouple component context tests from global resolver.
emberjs/ember.js pull request #15357
Opened 2017-06-13 18:34 UTC by patricksrobertson

This extracts the Application Lifecycle - Component Context tests
from the component registration tests and then rewrites them to use
the TestModuleResolver.

side note: I have no idea what I'm doing here.

2017-06-13 23:41 UTC, mixonic requested changes
@patricksrobertson this is a solid start thank you! I made a few notes of how to clean it up to be ready for a merge.

This commits should be squashed as well.

2017-06-13 23:41 UTC, mixonic commented on packages/ember/tests/component_context_test.js
> +      assert.equal(jQuery('#wrapper').text(), 'inner-outer', 'The component is composed correctly');
`jQuery` here can be replaced with: `this.$('#wrapper')`. The latter will scope the selector (and avoid importing `jQuery`). Also elsewhere through this patch.

2017-06-13 23:41 UTC, mixonic commented on packages/ember/tests/component_context_test.js
> +    }), template: '{{text}}-{{yield}}' });
Perhaps can this be formatted to be more legible?

```js
this.addComponent('my-component', {
  ComponentClass: Component.extend({
    text: 'inner'
  }),
  template: `{{text}}-{{yield}}`
});
```

2017-06-13 23:41 UTC, mixonic commented on packages/ember/tests/component_context_test.js
> +    this.addTemplate('application', '<div id=\'wrapper\'>{{#my-component}}<a href=\'#\' id=\'fizzbuzz\' {{action \'fizzbuzz\'}}>Fizzbuzz</a>{{/my-component}}</div>');
Wrapping the templates in backticks would avoid all the quote escaping here. In addition backticks would permit multiple lines:

```js
this.addTemplate('application', `
  <div id="wrapper">
    {{#my-component}}
      <a href="#" id="fizzbuzz" {{action 'fizzbuzz'}}>
        Fizzbuzz
      </a>
    {{/my-component}}
  </div>
`);
```

Much easier to grok.

2017-06-13 23:41 UTC, mixonic commented on packages/ember/tests/component_context_test.js
> +      run(() => jQuery('#fizzbuzz', '#wrapper').click());
runloop should not be needed here, or around any other `click` statements. `this.$('#fizzbuzz').click()` would be fine.

2017-06-14 16:19 UTC, patricksrobertson commented
@mixonic should be all set. Since we went with backticks for the templates, I opted to go:
```js
let text = this.$('#wrapper').text().trim()
assert.equal(text, ...)
```
to not change the assertions and to save line width.

2017-06-14 16:43 UTC, mixonic approved these changes

2017-06-14 16:43 UTC, merged

2017-06-14 16:44 UTC, mixonic commented
Excellent! Thank you @patricksrobertson :-)