cleanup `computed.teardown`
emberjs/ember.js pull request #15407
Opened 2017-06-25 04:44 UTC by bekzod

2017-06-25 04:45 UTC, bekzod commented on packages/ember-metal/lib/computed.js
> -  let meta = metaFor(obj);
it is pure speculation, I think it should be `peekMeta`

2017-06-25 17:13 UTC, stefanpenner requested changes

2017-06-25 17:13 UTC, stefanpenner commented on packages/ember-metal/lib/computed.js
> -  let meta = metaFor(obj);
yup this is correct, but we will now need to guard against `meta === null`.

something like
```js
+  let meta = _meta || peekMeta(obj);
 
if ( meta === null) { return; }
```

2017-06-25 17:14 UTC, stefanpenner commented on packages/ember-metal/lib/computed.js
> -  let meta = metaFor(obj);
another question though is, if teardown isn't public and the only place we call it we already provide meta, then maybe we don't need to do a meta lookup at all? What are your thoughts?

2017-06-25 17:31 UTC, bekzod commented on packages/ember-metal/lib/computed.js
> -  let meta = metaFor(obj);
sure...doing that

2017-06-25 19:13 UTC, stefanpenner requested changes

2017-06-25 19:13 UTC, stefanpenner commented on packages/ember-metal/lib/computed.js
> +  if (this._volatile || !meta) {
i believe it may be impossible for `meta` to be null here. Or..?

2017-06-25 19:15 UTC, bekzod commented on packages/ember-metal/lib/computed.js
> +  if (this._volatile || !meta) {
I believe too ... so no guard ?

2017-07-02 16:54 UTC, stefanpenner approved these changes

2017-07-02 16:55 UTC, stefanpenner commented
restarting sauce

2017-07-03 00:44 UTC, locks commented
![image](https://user-images.githubusercontent.com/32344/27774810-30082096-5f91-11e7-863a-d7bfde385a32.png)

2017-07-03 04:39 UTC, merged