reuse empty func in `ember-debug`
emberjs/ember.js pull request #15413
Opened 2017-06-25 19:29 UTC by bekzod

2017-06-25 20:50 UTC, stefanpenner requested changes

2017-06-25 20:50 UTC, stefanpenner commented on packages/ember-debug/lib/index.js
> +const noop = () => {};
thoughts on `const noop = assert = info = /*.... etc */`?

2017-06-26 11:14 UTC, bekzod commented on packages/ember-debug/lib/index.js
> +const noop = () => {};
tried, its failed travis, (there was some weirdness to it I forgot), so reverted to initial per line approach

2017-06-26 21:39 UTC, stefanpenner approved these changes

2017-06-26 21:39 UTC, merged