removed redundant check in `removeListener`
emberjs/ember.js pull request #15424
Opened 2017-06-27 19:15 UTC by bekzod

2017-06-27 19:16 UTC, bekzod commented on packages/ember-metal/lib/events.js
> -    if ('function' === typeof obj.didRemoveListener) {
callback is checked for being `function` inside `meta. removeFromListeners ` already

2017-06-27 20:39 UTC, stefanpenner requested changes

2017-06-27 20:39 UTC, stefanpenner commented on packages/ember-metal/lib/events.js
> +  metaFor(obj).removeFromListeners(eventName, target, method, obj.didRemoveListener);
this will result in `didRemoveListener` being invoked without a `this`

2017-06-28 04:14 UTC, bekzod commented on packages/ember-metal/lib/events.js
> +  metaFor(obj).removeFromListeners(eventName, target, method, obj.didRemoveListener);
oops..... I remade what I did.... it is better that before I think

2017-06-28 04:16 UTC, bekzod commented on packages/ember-metal/lib/events.js
> +    obj.didRemoveListener.bind(obj) : ()=> {};
* avoids creating wrapping function
* does not do `if check` each cycle
* does not convert arguments to array
* does not do work when `obj.didRemoveListener` missing

2017-06-28 15:25 UTC, stefanpenner approved these changes

2017-06-28 15:25 UTC, stefanpenner commented on packages/ember-metal/lib/events.js
> +    obj.didRemoveListener.bind(obj) : ()=> {};
bind is heavily optimized in modern, this may be a good idea.

2017-06-28 18:19 UTC, krisselden commented
we should be using bind, not creating closures.  only reason in the past for not doing it was phantom, I don't think that is a good reason

2017-06-29 16:18 UTC, merged