bump rsvp
emberjs/ember.js pull request #15441
Opened 2017-06-30 15:08 UTC by bekzod

2017-06-30 16:34 UTC, rwjblue commented
can you also update the package.lock?

2017-06-30 16:41 UTC, bekzod commented
What is proper way of generating yarn.lock ? I do just yarn install thats all

2017-06-30 19:21 UTC, bekzod commented
done

2017-07-03 04:24 UTC, bekzod commented
just needs restart I think

2017-07-04 14:17 UTC, bekzod commented
needs restart again

2017-07-04 15:15 UTC, stefanpenner requested changes

2017-07-04 15:15 UTC, stefanpenner commented on package.json
> -    "rsvp": "^3.5.0",
3.6.1, my bad

2017-07-04 15:38 UTC, bekzod commented
green

2017-07-04 15:41 UTC, merged