Decouple substate tests from the global resolver.
emberjs/ember.js pull request #15448
Opened 2017-07-03 18:51 UTC by patricksrobertson

I've moved this into three different test modules:

* A default state that relies on the visit API.
* A nested route module that has shared setup for roughly half the tests
* An AutobootTestCase module for dealing with the one test case that
cannot be worked around.

I've removed the step testing function. This seemed to be more important
for debugging the authoring of the original sets of tests instead of
actually asserting code.

The instance of 'BRO' has been replaced with 'TURTLE' because I hate fun
and value inclusivity.

Refs #15058

2017-07-03 23:40 UTC, mixonic requested changes
One or two things I would appreciate your thoughts on. Great start on a large migration, thank you.

I'd push your edits even further and swap `smells` for `cats` ;-)

2017-07-03 23:40 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> -      step(2, 'ApplicationRoute#setup');
Isn't some coverage lost by dropping these `step` assertions for what hooks fire in what order?

2017-07-03 23:40 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> +    this.visit('/grandma/mom/sally');
Please prefer the promise version of `visit`:

```js
return this.visit('/grandma/mom/sally').then(() => {
  let text = this.$('#app').text();
  /* ... */
});
```

2017-07-03 23:40 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> +  ['@test Slow promises returned from ApplicationRoute#model enter ApplicationLoadingRoute if present - NEW'](assert) {
Isn't this the same test?

* https://github.com/emberjs/ember.js/pull/15448/files#diff-a6a3e15b340e41ccc770054658e38485L733

Why `NEW` in the name?

2017-07-03 23:40 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> -QUnit.test('Enter loading route if only LoadingRoute defined', function() {
Is this test missing in the refactored file?

2017-07-03 23:40 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> +      this.visit('/grandma/smells');
Should return the promise here and chain.

```js
  return this.visit('/grandma/smells');
}).then(() => {
  let appController = this.getController('application');
  assert.equal(appController.get('currentPath'), 'grandma.loading', /* ... */
```

2017-07-03 23:40 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> +    );
Doesn't the original test attempt a `transitionTo` on the router after this?

* https://github.com/emberjs/ember.js/pull/15448/files#diff-a6a3e15b340e41ccc770054658e38485L1039

2017-07-04 04:33 UTC, karthiick commented on packages/ember/tests/routing/substates_test.js
> +          ok(true, 'loading action received on ApplicationRoute');
missed assert

2017-07-04 12:47 UTC, patricksrobertson commented on packages/ember/tests/routing/substates_test.js
> +    this.visit('/grandma/mom/sally');
The problem is that the visit promise will not resolve until the model hook promise is resolved.

Is there another pattern to follow ie:
```js
let visit = this.visit('grandma/mom/sally');
// assertion before model is resolved
model.resolve();
visit.then(() => {
  //assertion after model hook is resolved
});
```

2017-07-04 12:48 UTC, patricksrobertson commented on packages/ember/tests/routing/substates_test.js
> +      this.visit('/grandma/smells');
same thing here as above ^, this relies on assertions before and after promises are resolved on `model()` hooks in routes.

2017-07-04 12:49 UTC, patricksrobertson commented on packages/ember/tests/routing/substates_test.js
> +    );
I can add that back in, my $0.02 is that you're testing behavior well tested in the basic routing test with that second assertion at the cost of pretty gnarly testing setup.

2017-07-04 12:49 UTC, patricksrobertson commented on packages/ember/tests/routing/substates_test.js
> -      step(2, 'ApplicationRoute#setup');
Fair point!

2017-07-04 12:50 UTC, patricksrobertson commented on packages/ember/tests/routing/substates_test.js
> +  ['@test Slow promises returned from ApplicationRoute#model enter ApplicationLoadingRoute if present - NEW'](assert) {
Shoot. The `- NEW` was when I was migrating tests over I could tell which of the two copies were failing. Will clean it out.

2017-07-05 13:23 UTC, patricksrobertson commented on packages/ember/tests/routing/substates_test.js
> -QUnit.test('Enter loading route if only LoadingRoute defined', function() {
https://github.com/emberjs/ember.js/pull/15448/files#diff-a6a3e15b340e41ccc770054658e38485R106

2017-07-05 15:37 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> +    this.visit('/grandma/mom/sally');
Yeah that would works well. The thing I was reaching for was to chain the promises, and your example does that. Another alternative:

```js
let promise = this.visit('/grandma/mom/sally').then(() => {
  let text = this.$('#app').text();
});
model.resolve();
return promise;
```

2017-07-14 20:25 UTC, mixonic requested changes
Just some small cleanup and I think this is good to go.

2017-07-14 20:25 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> +    );
Yeah but it also is asserting that you can transition after an error substate. I'd prefer to add it back in.

2017-07-14 20:25 UTC, mixonic commented on packages/ember/tests/routing/substates_test.js
> +        foo.bar_loading was entered (as opposed to something like
Seems odd for an assertion message to start with a newline. Would prefer:

```js
  assert.equal(
    text, 'FOOBAR LOADING',
    `foo.bar_loading was entered (as opposed to something like foo/foo/bar_loading`
  );
```

2017-07-14 21:18 UTC, patricksrobertson commented
@mixonic addressed!

2017-08-16 23:33 UTC, mixonic approved these changes

2017-08-16 23:33 UTC, merged