correct checking `args` and cleanup in `mixins/array`
emberjs/ember.js pull request #15440
Opened 2017-06-30 11:13 UTC by bekzod

2017-06-30 11:15 UTC, bekzod commented on packages/ember-runtime/lib/mixins/enumerable.js
> -        ret[idx] = args ? method.apply(x, args) : x[methodName]();
here `args` is always array

2017-06-30 14:50 UTC, stefanpenner commented
awesome. Geeze that sauce test is driving us crazy. @bekzod do you have any free cycles to investigate whats going on there? It seems the stability of our sauce tests have gone down recently.

2017-06-30 14:52 UTC, bekzod commented
@stefanpenner I will have a look, sure

2017-07-06 13:27 UTC, bekzod commented on packages/ember-utils/lib/invoke.js
> +    return applyStr(obj, methodName, args);
there is already `args` existence check inside  `applyStr`

2017-07-06 13:34 UTC, bekzod commented on packages/ember-runtime/lib/mixins/array.js
> +  return obj && obj[EMBER_ARRAY];
[EMBER_ARRAY] === true

2017-07-14 03:08 UTC, krisselden requested changes
looks good

2017-07-14 03:08 UTC, krisselden commented on packages/ember-runtime/lib/mixins/array.js
> +  return content.objectAt ? content.objectAt(idx) : content[idx];
typeof content.objectAt === 'function'

2017-07-14 03:17 UTC, bekzod commented on packages/ember-runtime/lib/mixins/enumerable.js
> +        ret[idx] = args.length ? method.apply(x, args) : x[methodName]();
@krisselden maybe it should be just `method.apply(x, args)` without args check ?

2017-07-24 13:15 UTC, bekzod commented on packages/ember-runtime/lib/mixins/enumerable.js
> -        ret[idx] = args ? method.apply(x, args) : x[methodName]();
maybe just default to `method.apply(x, args)` always here ?

2017-08-07 18:16 UTC, krisselden approved these changes

2017-08-12 18:56 UTC, merged