Begin Decoupling the basic routing test from the Global resolver.
emberjs/ember.js pull request #15460
Opened 2017-07-05 17:20 UTC by patricksrobertson

It is generally agreed upon that human beings lack the ambition to
rewrite 3800 lines of test code in one sitting, which mirrors the
inability to review 3800 lines of code. In order to make progress
on the basic routing tests, this PR does:
* Creates a new module using ApplicationTestCase for the first ten
basic tests.
* Adds the module to a temporary file name
* Uses more modern convienence methods for determining currentPath.
* Asserts based upon template text instead of selector length.

2017-07-05 18:14 UTC, alexander-alvarez commented on packages/ember/tests/routing/decoupled_basic_test.js
> +  ['@test warn on URLs note included in the route set'](assert) {
not

2017-07-05 18:15 UTC, alexander-alvarez commented on packages/ember/tests/routing/decoupled_basic_test.js
> +  [`@test an Alternate template will pull
An alternate

2017-07-14 20:34 UTC, mixonic requested changes
Small formatting things mostly. This is excellent!

2017-07-14 20:34 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +    is set as controller's model`](assert) {
Can this not be wrapped? newline in a test name seems odd.

2017-07-14 20:34 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +    in renderTemplate and controller`](assert) {
Same here.

2017-07-14 20:34 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +    alternate controller via key/value`](assert) {
And here

2017-07-14 20:34 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +    alternate controller instead of controllername`](assert) {
And here.

2017-07-14 20:34 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +    in an alternate controller`](assert) {
and here.

2017-07-14 20:34 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +    template name in renderTemplate`](assert) {
and another

2017-07-14 20:34 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +    page with multiple Router.map calls`](assert) {
and here.

2017-07-14 20:54 UTC, patricksrobertson commented on packages/ember/tests/routing/decoupled_basic_test.js
> +  ['@test defining templateName allows other templates to be rendered'](assert) {
From here on are additional tests.

2017-07-14 20:55 UTC, patricksrobertson commented on packages/ember/tests/routing/decoupled_basic_test.js
> +  ['@test defining templateName allows other templates to be rendered'](assert) {
@mixonic sorry, was currently adding more stuff to the file while you started the PR review. There are 5 more tests added at the end. Should be non-controversial edits.

2017-08-16 23:17 UTC, mixonic approved these changes
I left two small test title comments, the rest of this looks fantastic. 🙇 Thank you for your patience.

2017-08-16 23:17 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +  [`@test The Homepage with explicity template name in renderTemplate`](assert) {
`explicity` => `explicit`

2017-08-16 23:17 UTC, mixonic commented on packages/ember/tests/routing/decoupled_basic_test.js
> +  [`@test An alternate template will pull in an alternate controller instead of controllername`](assert) {
`controllerName`? Weird test title anyway, not sure why any variant of `controllername` needs to be in it.

2017-08-16 23:45 UTC, mixonic commented
I'm kicking sauce to get things passing. We should be sure to remove the `decoupled_basic_test` back to `basic_test` when we're done here.

2017-08-16 23:55 UTC, merged