Delete controller_content_model_alias_deprecation.js
emberjs/ember.js pull request #15528
Opened 2017-07-19 16:41 UTC by locks

2017-07-19 16:54 UTC, rwjblue requested changes

2017-07-19 16:54 UTC, rwjblue commented on packages/ember-runtime/lib/mixins/controller.js
> +  content: deprecatingAlias('model')
This will need an options hash with id, until, description, etc

2017-07-19 16:55 UTC, rwjblue commented
Can you also remove the entry in features.json?

2017-07-22 02:32 UTC, locks commented
@rwjblue please re-review and 👀 the commit message for correctness 🙇

2017-07-22 13:53 UTC, rwjblue reviewed
Looks good. Happy to land when green, but we still need to follow up with the deprecation guide stuff for the newly added deprecation.

2017-07-22 13:53 UTC, rwjblue commented on packages/ember-runtime/lib/mixins/controller.js
> +  content: deprecatingAlias('model', { id: 'ember-runtime.controller-content', until: '2.16.0' })
We also need to add a deprecation guide entry to the website and add a `url` property with the link.

2017-07-31 01:10 UTC, locks commented on packages/ember-runtime/lib/mixins/controller.js
> +  content: deprecatingAlias('model', { id: 'ember-runtime.controller-content', until: '2.16.0' })
deprecation guide PRed: https://github.com/emberjs/website/pull/2969

2017-08-03 16:41 UTC, rwjblue approved these changes

2017-08-03 17:19 UTC, merged