Missed code block added in comments
emberjs/ember.js pull request #15542
Opened 2017-07-24 11:55 UTC by kumkanillam

2017-07-24 14:50 UTC, locks commented on packages/ember-routing/lib/system/route.js
> +	```
Can you add a newline after the code block?

2017-07-24 14:50 UTC, locks requested changes

2017-07-24 14:50 UTC, locks commented on packages/ember-routing/lib/system/route.js
> +	```
Can you add a newline after the code block?

2017-07-24 15:04 UTC, kumkanillam commented on packages/ember-routing/lib/system/route.js
> +	```
done @locks

2017-07-24 15:10 UTC, locks commented on packages/ember-routing/lib/system/route.js
> +	```
Can you squash the commits and prefix the commit with `[DOC release]`?

2017-07-25 12:01 UTC, kumkanillam commented on packages/ember-routing/lib/system/route.js
> +	```
done @locks

2017-07-25 12:39 UTC, locks approved these changes

2017-07-25 12:39 UTC, merged

2017-07-25 12:40 UTC, locks commented
Thank you :)