avoid boolean coarsion
emberjs/ember.js pull request #15553
Opened 2017-07-27 08:58 UTC by bekzod

2017-07-27 15:19 UTC, stefanpenner commented
restarting

2017-07-29 17:59 UTC, locks commented
@stefanpenner it's green

2017-08-03 00:43 UTC, krisselden requested changes
Other than the one issue, looks good.

2017-08-03 00:43 UTC, krisselden commented on packages/ember-metal/lib/chains.js
> +  if (meta === undefined || meta.readableChainWatchers() === undefined) {
there is falsy coercion above this in `let meta = _meta || peekMeta(obj);`

2017-08-11 20:15 UTC, krisselden commented
it's spelled coercion in case you want to update the commit messages

2017-08-12 15:33 UTC, merged

2017-08-12 15:33 UTC, rwjblue commented
Thanks @bekzod !