[Refactor]: Align component manager's methods with RFC
emberjs/ember.js pull request #15628
Opened 2017-09-04 05:40 UTC by twokul

Before this change, when defining a custom component manager, you'd have to define `layoutFor` (or extend from `AbstractComponentManager`)  for components to render properly. After this change, you'd have to define only 3 methods (as per [RFC](https://github.com/emberjs/rfcs/blob/custom-components/text/0000-custom-components.md)): `create`, `getSelf` (`getContext` in RFC) and `update`. This commit does not change existing behaviour.

Changes:
+ introduce a new "wrapper" class for custom component managers. `layoutFor` mimics the behaviour of curly components and `create`, `getSelf` and `update` are left for developers to define
+ tests

Relevant links:
+ [Custom Components RFC](https://github.com/emberjs/rfcs/blob/custom-components/text/0000-custom-components.md)

2017-09-05 13:31 UTC, rwjblue requested changes

2017-09-05 13:31 UTC, rwjblue commented on packages/ember-glimmer/lib/component-managers/custom.js
> +      throw new Error('You must implement `create` method.');
These errors should be dev only assertions

2017-09-05 13:31 UTC, rwjblue commented on packages/ember-glimmer/lib/component-managers/custom.js
> +      throw new Error('You must implement `getSelf` method.');
☝️

2017-09-05 13:31 UTC, rwjblue commented on packages/ember-glimmer/lib/component-managers/custom.js
> +      throw new Error('You must implement `update` method.');
⬆️

2017-09-07 15:31 UTC, twokul commented
per conversation with @rwjblue:
+ we should likely add [optional features](https://github.com/emberjs/rfcs/blob/custom-components/text/0000-custom-components.md#optional-features) w/o assertions;
+ possibly move public methods validation (assertions) into a constructor `CustomManager`

2017-10-26 13:53 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/custom-component-manager-test.js
> +      assert.throws(() => {
Have to change this to `expectAssertion` (since we don't throw in production).

2017-10-26 13:53 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/custom-component-manager-test.js
> +      assert.throws(() => {
Same as above

2017-10-26 13:53 UTC, rwjblue commented on packages/ember-glimmer/tests/integration/custom-component-manager-test.js
> +      assert.throws(() => {
🆙

2017-10-28 16:56 UTC, twokul commented on packages/ember-glimmer/lib/component-managers/abstract.ts
> +  abstract templateFor(
@krisselden does this change look sound to you?

2018-02-24 03:41 UTC, rwjblue commented
Reworking internals (and RFC), changes will come in a future PR...

2018-02-24 03:41 UTC, closed without merging