refactor `ObserverSet` use Map
emberjs/ember.js pull request #15928
Opened 2017-12-06 12:32 UTC by bekzod

2017-12-06 17:36 UTC, rwjblue requested changes

2017-12-06 17:36 UTC, rwjblue commented on packages/ember-metal/lib/observer_set.js
> -/*
This comment was useful (in general) for explaining the internal data structure used in `ObserverSet`.  Can you bring back a new comment that shows what things look like now?

2017-12-06 17:36 UTC, rwjblue commented on .eslintrc.js
> +    'Map': true,
👍

2018-01-28 07:26 UTC, bekzod commented
already covered here #16187

2018-01-28 07:26 UTC, closed without merging