small optimization to `getPath` and `setPath`
emberjs/ember.js pull request #16235
Opened 2018-02-11 08:15 UTC by bekzod

2018-02-11 08:24 UTC, bekzod commented on packages/ember-metal/lib/property_set.js
> +    return _set(newRoot, keyName, value);
using `_set` here to avoid `isPath` check

2018-02-11 08:24 UTC, bekzod commented on packages/ember-metal/lib/property_get.js
> +    obj = _get(obj, parts[i]);
using `_get` here to avoid `isPath` check

2018-02-11 09:19 UTC, bekzod commented
surprising benchmark results :) https://cl.ly/1Z3d0R3I3k0y/results.pdf

2018-02-12 06:45 UTC, mmun commented
This looks great! Can you rename _get/_set to _getKey/_setKey to align with watch/watchKey/watchPath. Similarly, for 💅, I think we can drop the underscores on _getKey/_setKey/_getPath/_setPath.

2018-02-12 20:22 UTC, mmun commented
@bekzod I just realized that it was _slower_ rather than _faster_. I'll have to take a closer look at what's going on before merging.

BTW you can just remove the _getPath export as well as the test for its presence.

2018-02-12 20:23 UTC, rwjblue commented
> BTW you can just remove the _getPath export as well as the test for its presence.

Good idea, @mmun...

2018-02-13 07:18 UTC, bekzod commented
with 80 samples same results https://cl.ly/2z2G0X0x0w1C/results.pdf will check other variations of code

2018-02-24 22:09 UTC, mmun commented
@rwjblue I haven't looked into it since. I'm also curious...

2018-02-28 18:54 UTC, bekzod commented
results look better if we drop `isPath` cache https://cl.ly/1q0G0r182I2h/results.pdf

2018-03-01 20:08 UTC, bekzod commented
needs another benchmark, prior benchmark was done on bad code (which failed tests)

2018-03-24 17:29 UTC, krisselden approved these changes

2018-03-29 20:15 UTC, bekzod commented
@krisseldon will be first thing that i do in the morning, last time I checked performed same as old code nothing huge

2018-03-29 20:34 UTC, rwjblue commented
@bekzod - When you take a look, you will need to rebase also...

2018-03-30 06:13 UTC, bekzod commented
after rebase got test failing for `Application, default resolver with autoboot / @test acts like a namespace`

2018-04-02 11:11 UTC, locks commented
Might be related to this? https://github.com/emberjs/ember.js/pull/16446/files

2018-04-02 11:13 UTC, bekzod commented
@locks it was failing before that change and after same thing, so not related I think

2018-04-25 14:09 UTC, bekzod commented
all green, issue was assertion in wrong place which was striped in prod so earlier bench is still valid

2018-05-01 18:55 UTC, krisselden requested changes
Overall I would like to drop the isPath cache if it isn't buying us much but one thing I'm remembering is originally we had it like this, but it was faster to check if the key was a miss before checking isPath.  I'm for trying this again, but wondering if it would be better to add an isPath arg to get to override whether the indexOf check is done again.  Also wonder if caching splits would be better than caching isPath. Also if the isPath cache limit was too low.

It would be good to gather get() calls from some apps and make a microbenchmark for this.  The microbenchmark could still add some pollution at the start.

2019-01-03 11:34 UTC, bekzod commented
made separate PR #17422 that makes this redundant

2019-01-03 11:34 UTC, closed without merging