correct changeProperties to be public API
emberjs/ember.js pull request #16303
Opened 2018-02-28 11:39 UTC by BryanCrotaz

Replaces #16302 

See @mmun comment in https://github.com/emberjs/ember.js/issues/16292#issuecomment-369129781

> But you shouldn't use those functions because they are private. You should be using object.setProperties(...) or
> 
> changeProperties(() => {
>   doStuff();
> });
> which does the try-finally for you. (Hmm, unfortunately it looks like changeProperties is accidentally marked private.)

2018-02-28 12:05 UTC, rwjblue commented
We also need to decide what the module API is for this before landing (and ensure the docs properly reference the module).

2018-02-28 12:55 UTC, BryanCrotaz commented
I would have thought the most logical place would be `Ember.Observable`

2018-02-28 16:15 UTC, mmun commented
This should be a global function, not a method. Leaving it as a method seems likely to confuse people and not realize that it actually has global behaviour.

2018-03-03 12:53 UTC, BryanCrotaz commented
In @ember/application?

2018-03-03 17:27 UTC, rwjblue requested changes

2018-03-03 19:28 UTC, BryanCrotaz commented on packages/ember-runtime/lib/mixins/observable.js
> +  changeProperties(callback) {
I was following the same pattern as the other observable functions. Where should I put it instead?

2018-03-03 22:37 UTC, rwjblue commented on packages/ember-runtime/lib/mixins/observable.js
> +  changeProperties(callback) {
We should ultimately deprecate those. It doesn’t make sense to expose these methods on an individual object, it gives the wrong signal (these are _not_ limited to the specific object and instead are global).

2018-03-03 23:25 UTC, BryanCrotaz commented
So this should go in ember application?

2018-04-22 15:33 UTC, BryanCrotaz commented
Where should this go?

2021-03-20 20:56 UTC, sandstrom commented
With changeProperties and setProperties being on their way out (along with the transition to ES6 classes instead of EmberObject), I'd guess this is less relevant now.

Maybe we can simply close this PR?

2021-03-22 18:33 UTC, rwjblue commented
Ya, good idea @sandstrom.

Thanks for working on this @BryanCrotaz!

2021-03-22 18:33 UTC, closed without merging