Rename private property Route#router to Router#_router
emberjs/ember.js pull request #16312
Opened 2018-03-02 18:33 UTC by cibernox

The fact that this private property was named router was preventing user
from injecting the router service into routes like this:

```js
export default Route.extend({
  router: service()
});
```

I consider that the above code is pretty reasonable, and it should be
the private property the one that should be renamed to a clearer `_router`
name that is less likely to collide with user-defined properties or methods.

If you deem this an _intimate_ API we could consider adding a deprecated
alias, but I don't have evidence to consider it such, as `router` is too
common of a term to search for in emberobserver.

Closes #16088

2018-03-02 18:39 UTC, cibernox commented
@Serabe ^

2018-03-02 18:44 UTC, rwjblue requested changes
Yes, I think we need to deprecate `this.router` in `Ember.Route` instances (and add an entry on the website to describe how to handle the deprecation). 

When folks inject the router service, it would clobber this "deprecating getter" and things should work just fine...

2018-03-02 18:46 UTC, cibernox commented
Working on it

2018-03-02 19:35 UTC, cibernox commented
@rwjblue Done. I considered this a bugfix beta and I added the deprecation in 3.1, but let me know if you prefer it to stay in canary and go in 3.2.

2018-03-19 13:26 UTC, rwjblue approved these changes

2018-03-19 13:28 UTC, rwjblue commented
> let me know if you prefer it to stay in canary and go in 3.2

yeah, lets move to 3.2 on the deprecations app.  I don't want to land a last minute deprecation just before release that ends up souring the yummy goodness of 3.1...

2018-03-19 13:39 UTC, cibernox commented
@rwjblue Documented in the new deprecations app in https://github.com/ember-learn/deprecation-app/pull/106

Updated this PR so the URL points to the right anchor in the new app.

2018-03-19 16:06 UTC, merged