[CLEANUP] Refactor some array stuff
emberjs/ember.js pull request #16392
Opened 2018-03-22 20:06 UTC by mmun

Some initial refactoring of the array code. This is the first step towards extracting out the array functions like replace, pushObjects, etc.

2018-03-22 20:09 UTC, mmun commented on packages/ember-runtime/lib/mixins/array.js
> +  replace(start, deleteCount, items = EMPTY_ARRAY) {
The logic here slightly changed so that `null` will trigger the assertion now. I consider that a bugfix...

2018-03-22 20:11 UTC, mmun commented on packages/ember-metal/lib/array.js
> +  }
Most of this file is a direct copy and paste from packages/ember-runtime/lib/mixins/array.js, although I did rewrite `replaceInNativeArray` to be a bit simpler.

2018-03-22 21:51 UTC, rwjblue requested changes

2018-03-22 21:51 UTC, rwjblue commented on packages/ember-metal/lib/array.js
> +const EMPTY_ARRAY = [];
Can we freeze this?

2018-03-22 21:51 UTC, rwjblue commented on packages/ember-runtime/lib/mixins/array.js
> +const EMPTY_ARRAY = [];
freeze plz

2018-03-23 13:33 UTC, rwjblue approved these changes

2018-03-23 13:33 UTC, merged