some cleanup of CoreObject
emberjs/ember.js pull request #16443
Opened 2018-03-30 16:50 UTC by krisselden

2018-03-30 18:40 UTC, rwjblue commented
```
Test failed: Mixin#reopen:  using reopen() and calling _super where there is not a super function does not cause infinite recursion
    Failed assertion: expected: Breakfast!, but was: Your breakfast was interrupted by an infinite stack error.
    at _class.testUsingReopenAndCalling_superWhereThereIsNotASuperFunctionDoesNotCauseInfiniteRecursion [as @test using reopen() and calling _super where there is not a super function does not cause infinite recursion] (http://localhost:13141/ember-tests.js:46147:14)
    at Object.<anonymous> (http://localhost:13141/ember-tests.js:82042:31)
    at runTest (http://localhost:13141/qunit/qunit.js:1478:30)
    at Test.run (http://localhost:13141/qunit/qunit.js:1464:6)
    at http://localhost:13141/qunit/qunit.js:1670:12
    at Object.advance (http://localhost:13141/qunit/qunit.js:1116:26)
```

2018-03-31 12:19 UTC, rwjblue requested changes

2018-03-31 12:19 UTC, rwjblue commented on packages/ember-runtime/lib/system/core_object.js
> +// should use WeakSet
Now that the PR moving weakset polyfill into Ember-utils package has landed, I think this can be updated

2018-04-10 14:01 UTC, rwjblue commented
@krisselden - I'd hate to lose track of these changes, anything I can do to help?

2018-06-21 04:05 UTC, krisselden commented
this is superseded by #16757

2018-06-21 04:05 UTC, closed without merging