Null check for calculateToString method
emberjs/ember.js pull request #16478
Opened 2018-04-10 08:31 UTC by lifeart

Issue found in: https://travis-ci.org/emberjs/ember-inspector/jobs/364445291

2018-04-10 11:03 UTC, rwjblue requested changes
Seems good, can you create a regression test here that roughly simulates what the inspector is doing?

2018-04-10 13:16 UTC, rwjblue commented
Thank you for the added test! I'm still having trouble figuring out how this can actually happen though. Generally speaking, the following is being done:

```js
class Foo {}
Foo.prototype.toString = classToString;
```

How is it, in this circumstance, that you would have the `toString` function without a `this`?

2018-04-10 13:44 UTC, rwjblue commented
After a bit of digging, it _seems_ like the ember-inspector is essentially doing this (in the test that was failing from the CI log above):

```js
let obj = Ember.Object.create();
let mixins = Ember.Mixin.mixins(obj);
let mixinDetails = [];
mixins.forEach(mixin => {
  let name = mixin[Ember.NAME_KEY] || mixin.ownerConstructor;
  if (!name && typeof mixin.toString === 'function') {
    name = mixin.toString();
  }
  if (!name) {
    name = 'Unknown mixin';
  }
  mixinDetails.push({
    name: name.toString(), 
    properties: propertiesForMixin(mixin),
  });
});
```

Basically, what is going on is that the inspector is trying to call `.toString()` on each mixin and the current guard only checks for `Function.prototype` to break out of the loop which (since `this` is an instance at that point it would need to check for `Object.prototype` to break the loop).

2018-04-10 13:49 UTC, rwjblue requested changes

2018-04-10 13:49 UTC, rwjblue commented on packages/ember-metal/tests/namespace_search_test.js
> +      result = classToString(F.bind(null));
Can you update the regression test to do roughly:

```js
let mixin = Mixin.create();
mixin.toString(); // without the fix, this throws
```

2018-04-10 13:49 UTC, rwjblue commented on packages/ember-metal/lib/namespace_search.js
>        if (superclass === Function.prototype) {
Can you update this to be:

```js
if (superclass === Function.prototype || superclass === Object.prototype) {
  break;
}
```

2018-04-10 13:49 UTC, rwjblue commented on packages/ember-metal/lib/namespace_search.js
> +      if (superclass === null) {
If we add `Object.prototype` check (mentioned in another comment) we can remove the explicit `null` check..

2018-04-10 13:51 UTC, rwjblue commented
Sorry for the run around here @lifeart, thank you for working on it!

2018-04-10 15:37 UTC, lifeart commented
@rwjblue `How is it, in this circumstance, that you would have the toString function without a this?`
https://github.com/emberjs/ember-inspector/pull/781/files#diff-7c2c7ea1dfc0ef384d1ec6e685711d15R480

2018-04-11 19:47 UTC, rwjblue commented
OK, looks great, would you mind squashing down to a single commit and prefixing the commit message with `[BUGFIX release]`?

2018-04-11 20:54 UTC, closed without merging