correct conditionals in `lib/component`
emberjs/ember.js pull request #16562
Opened 2018-04-21 14:51 UTC by bekzod

2018-04-21 14:57 UTC, rwjblue reviewed
Does this fix any specific thing? Can we add a regression test for it?

2018-04-21 18:46 UTC, krisselden requested changes

2018-04-21 18:46 UTC, krisselden commented on packages/ember-glimmer/lib/component.ts
> +      if (reference && UPDATE in reference) {
lets not use then, use reference[UPDATE] !== undefined

2018-04-21 18:46 UTC, krisselden commented on packages/ember-glimmer/lib/component.ts
> +      if (reference && UPDATE in reference) {
in general we should avoid falsy conversions

2018-04-21 18:47 UTC, krisselden commented
@rwjblue he is just collapsing the if, there isn't change to behavior

2018-05-07 13:43 UTC, rwjblue requested changes

2018-05-07 13:43 UTC, rwjblue commented on packages/ember-glimmer/lib/component.ts
> +      if (reference !== undefined && UPDATE in reference) {
Can you update this to:

```js
if (reference !== undefined && reference[UPDATE] !== undefined) {
}
```

(no need to use `in` here AFAICT)

2018-05-17 18:31 UTC, krisselden approved these changes

2018-05-17 18:32 UTC, rwjblue approved these changes

2018-05-17 18:32 UTC, merged