[BUGFIX beta] computed.sort array should update if sort properties array is empty
emberjs/ember.js pull request #16632
Opened 2018-05-13 21:52 UTC by miguelcobain

Basically, when the sort properties array is empty, `computed.sort` was returning the original array, *but not* responding to any changes in that array.
The result was that any `computed.sort` never changed, even when the dependent array changed.

I hope the (previously failing) test is self explanatory.
Is there a chance we can backport this to previous ember versions?

Please let me know if anything else is needed from me. Thanks!

2018-05-13 23:11 UTC, miguelcobain commented
Failure is related to a Browserstack issue.

2018-05-16 18:30 UTC, rwjblue requested changes

2018-05-16 18:53 UTC, miguelcobain commented
@rwjblue feedback was applied 👍

2018-05-16 18:57 UTC, rwjblue approved these changes

2018-05-16 20:11 UTC, merged

2018-05-16 20:12 UTC, rwjblue commented
Thank you!