respect descriptor `configurable` property
emberjs/ember.js pull request #16727
Opened 2018-06-08 14:27 UTC by bekzod

2018-06-08 17:32 UTC, rwjblue reviewed
This seems like a new feature? Where are we using this? What do we need it for?

2018-06-08 20:22 UTC, bekzod commented
use case is simple disallow redefining property descriptor so `configurable: false` actually works for example `length` of `ArrayProxy` can be redefined if this PR merged and `length` property defined as `configurable: false` it will become non-redefineable :)    https://github.com/bekzod/ember.js/blob/99561cbbddccb12db41823fad3bb91ce281dcfd8/packages/ember-runtime/lib/system/array_proxy.js#L198
similarly there are several places in codebase that has descriptors  with `configurable: false`
https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/mixins/child_views_support.js#L16
https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/mixins/view_support.js#L154
also `isDestroyed` and `isDestroying` descriptors could be non configurable too,
https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/core_object.js#L263
so they are not redefined when extending object

2018-06-08 21:27 UTC, rwjblue commented
@krisselden - Thoughts?

2018-06-26 02:24 UTC, krisselden requested changes
This seems like a new feature masquerading as a BUGFIX, this kind of descriptor isn't public as far as I'm aware and we are trying to move to class syntax for get/set props.

2018-06-26 06:07 UTC, bekzod commented on packages/ember-metal/lib/mixin.ts
> +  keys.forEach(key => {
because `keys` is `Set` now

2018-06-28 02:28 UTC, krisselden commented on packages/ember-metal/lib/mixin.ts
> +  keys.forEach(key => {
we can't casually make that change without testing

2018-06-28 02:36 UTC, krisselden commented
We don't want to add anything to extending that doesn't align with ES2015 classes.  Property attributes do not inherit from a prototype property.

![image](https://user-images.githubusercontent.com/61024/42009958-6b9c8b08-7a41-11e8-91bf-b39ace91262a.png)

2018-06-28 02:36 UTC, closed without merging