Fix container destroy timing
emberjs/ember.js pull request #16754
Opened 2018-06-18 18:49 UTC by wagenet

2018-06-18 18:54 UTC, rwjblue requested changes
Need to tweak some other parts of the container destroy lifecycle also here, I'll get those changes pushed up into this PR shortly...

2018-06-18 19:11 UTC, stefanpenner submitted a review, later dismissed

2018-06-18 19:11 UTC, stefanpenner commented on packages/ember-runtime/lib/mixins/container_proxy.js
> +      schedule('destroy', this.__container__, 'destroy');
I think more `join` like behavior?

2018-06-20 17:21 UTC, rwjblue commented
Just pushed an update that should address the concerns that @krisselden / @stefanpenner brought up.

Should be good to land once green...

2018-06-20 18:07 UTC, wagenet reviewed
Looks ok. Only point of confusion I had is that `finalizeDestroy` isn't automatically called. Is that as expected? Obviously, this is internal API, but I could see someone potentially calling only `destroy` and never calling `finalizeDestroy`.

2018-06-20 18:23 UTC, rwjblue approved these changes

2018-06-20 18:30 UTC, merged

2018-06-20 18:46 UTC, rwjblue commented
> Only point of confusion I had is that finalizeDestroy isn't automatically called. Is that as expected? Obviously, this is internal API, but I could see someone potentially calling only destroy and never calling finalizeDestroy.

@wagenet - The container itself is not actually exposed, any user-land code calling `.destroy()` would be on the "owner" which is exactly the thing that mixes in `ContainerProxyMixin` and gets the `destroy` implementation in this PR.