cleanup `_lookupPartial`
emberjs/ember.js pull request #16793
Opened 2018-07-05 09:23 UTC by bekzod

2018-07-05 09:24 UTC, bekzod commented on packages/ember-glimmer/lib/resolver.ts
> -    if (modifier !== undefined) {
there is already `undefined` check downstream in `handle` method, so this looks unnecessary

2018-07-09 13:27 UTC, rwjblue requested changes

2018-07-10 06:29 UTC, bekzod commented
done

2018-07-12 23:06 UTC, krisselden approved these changes

2018-07-12 23:07 UTC, merged