[BUGFIX] Clear chains in ProxyMixin when destroyed
emberjs/ember.js pull request #16860
Opened 2018-08-03 12:10 UTC by pieter-v

When a ObjectProxy is destroyed while the proxied object is still alive, then the ObjectProxy is leaked because the chains attached to the proxied object retains the ObjectProxy.
This is an issue for us, as ember-data uses proxies for their belongsTo relationships. (See https://github.com/emberjs/data/pull/5554 for more information)

A sample program that demonstrates this can be found at https://github.com/pieter-v/ember-proxy-leak

A memory snapshot before this fix:
![before](https://user-images.githubusercontent.com/7090162/43642178-c8a9d2fe-9726-11e8-83b5-e6715755bdce.png)

A memory snapshot after this fix:
![after](https://user-images.githubusercontent.com/7090162/43642183-d2c6596a-9726-11e8-9f84-a3b0d84dae47.png)

2018-08-03 13:45 UTC, rwjblue commented on packages/ember-runtime/lib/mixins/-proxy.js
> +    this.set('content', null);
I'd prefer to set the content before supering. Do you see any issues with that?

2018-08-03 14:11 UTC, pieter-v commented
@rwjblue no problem, just left on a long weekend, will do it next Thursday

Op vr 3 aug. 2018 16:05 schreef Robert Jackson <notifications@github.com>:

> *@rwjblue* commented on this pull request.
> ------------------------------
>
> In packages/ember-runtime/lib/mixins/-proxy.js
> <https://github.com/emberjs/ember.js/pull/16860#discussion_r207548849>:
>
> > @@ -61,6 +61,11 @@ export default Mixin.create({
>      m.writableTag(() => combine([DirtyableTag.create(), UpdatableTag.create(CONSTANT_TAG)]));
>    },
>
> +  destroy() {
> +    this._super(...arguments);
> +    this.set('content', null);
>
> I'd prefer to set the content before supering. Do you see any issues with
> that?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/emberjs/ember.js/pull/16860#pullrequestreview-143186303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGwv8hD0MW9757n8Qkz0g6OtAZX4gID-ks5uNFiKgaJpZM4Vt37u>
> .
>

2018-08-03 14:41 UTC, rwjblue commented
Awesome, enjoy!

2018-08-04 06:40 UTC, krisselden requested changes
destroy should use ember set only willDestroy, destroy is only supposed to mark is destroying and schedule willDestroy which can set

2018-08-15 08:47 UTC, krisselden approved these changes

2018-09-05 08:30 UTC, pieter-v commented
rebased

2018-09-05 14:09 UTC, merged