Fix event dispatcher
emberjs/ember.js pull request #17804
Opened 2019-03-26 21:25 UTC by chancancode

TODO: make elementId optional

2019-03-26 22:46 UTC, rwjblue reviewed
Generally 👍, only had one small question

2019-03-26 22:46 UTC, rwjblue commented on packages/@ember/-internals/views/lib/system/utils.js
> +export function clearViewElement(view) {
Shouldn't this also remove from `ELEMENT_VIEW`? Seems _slightly_ odd to have this mismatch vs setViewElement

2019-03-28 03:28 UTC, wycats requested changes

2019-03-28 03:28 UTC, wycats commented on packages/@ember/-internals/views/lib/system/utils.js
> +// These are not needed for GC, but for correctness
Can you write a little more here?

2019-03-28 03:47 UTC, wycats submitted a review, later dismissed

2019-03-28 15:47 UTC, rwjblue submitted a review, later dismissed
LGTM

2019-03-29 18:11 UTC, mixonic commented
Should `-view-registry` go through an intimate API deprecation re: [usages in the wild](https://www.emberobserver.com/code-search?codeQuery=-view-registry&sort=usages&sortAscending=false)?

2019-04-01 15:33 UTC, rwjblue commented
> Should -view-registry go through an intimate API deprecation re: usages in the wild?

I did review usages on EmberObserver.com and I do not think the limited usage merits intimate API deprecation. The usages in addons that are maintained (releases in the last year or so) are mostly official packages (`@ember/test-helpers`, `ember-resolver` in the MU flagged code, etc), the usages in maintained non-official addons seem to mostly be in custom testing utilities and actually do have a nice API to migrate to.

2021-02-10 15:31 UTC, rwjblue commented
@chancancode - Should we close, or revive?

2021-02-10 18:23 UTC, chancancode commented
huh yes, I thought we did the elementId fix already.. did we not?

2021-02-10 18:50 UTC, chancancode commented
Ah we did in fact land #17818 at least. We can probably just remove this now since the inspector switched to using the debug render tree. (Though I just added a test in #19382 that uses the view registry because I was lazy. 😉)

2022-02-05 19:43 UTC, locks commented
@chancancode is this still relevant?

2023-12-12 16:20 UTC, kategengler commented
Is this still relevant? It is labeled `wip`.

2026-06-01 18:17 UTC, closed without merging

2026-06-01 18:17 UTC, kategengler commented
Closing as stale