[FEATURE beta] Passes the owner through to classic classes
emberjs/ember.js pull request #17858
Opened 2019-04-04 18:03 UTC by pzuraq

Implements https://github.com/emberjs/rfcs/pull/467, and fixes the error message so it won't throw if properties aren't passed (`new EmberObject()`)

2019-05-03 00:54 UTC, rwjblue commented
Just updated to more closely match https://github.com/emberjs/rfcs/pull/451, should be ready for review.

2019-05-07 16:53 UTC, chadhietala requested changes
Overall this looks good to me. Just a small nit.

2019-05-07 16:53 UTC, chadhietala commented on packages/@ember/-internals/runtime/lib/system/core_object.js
> +const initCalled = DEBUG ? new WeakSet() : undefined; // only used in debug builds to enable the proxy trap
I believe you are going to fail IE11 builds due to the usage of `WeakSet`.

2019-05-08 18:49 UTC, rwjblue approved these changes

2019-05-09 16:30 UTC, merged