Bumped Prettier from 1.16.4 to 1.18.0
emberjs/ember.js pull request #18083
Opened 2019-06-09 00:38 UTC by demersaj

2019-06-09 13:18 UTC, rwjblue commented
The update results in a few failures:

```
/home/travis/build/emberjs/ember.js/packages/@ember/-internals/container/lib/container.ts
  598:45  error  Replace `⏎··········this.normalizedName⏎········` with `this.normalizedName`  prettier/prettier
/home/travis/build/emberjs/ember.js/packages/@ember/-internals/glimmer/lib/modifiers/on.ts
  112:120  error  Replace `⏎········args.positional.length⏎······` with `args.positional.length`  prettier/prettier
/home/travis/build/emberjs/ember.js/packages/@ember/-internals/metal/lib/tracked.ts
  138:75  error  Replace `⏎··········propertyDesc.initializer⏎········` with `propertyDesc.initializer`  prettier/prettier
/home/travis/build/emberjs/ember.js/packages/@ember/-internals/routing/lib/system/route.ts
   256:23  error  Replace `⏎··········this.routeName⏎········` with `this.routeName`  prettier/prettier
  2367:89  error  Replace `⏎········this.routeName⏎······` with `this.routeName`      prettier/prettier
/home/travis/build/emberjs/ember.js/packages/@ember/-internals/routing/lib/system/router.ts
   516:75   error  Replace `⏎··········args[0]⏎········` with `args[0]`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        prettier/prettier
   525:43   error  Replace `⏎········this.currentRouteName⏎······` with `this.currentRouteName`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                prettier/prettier
   962:123  error  Replace `⏎················qpOther.scopedPropertyName⏎··············}\`·and·\`${⏎················qp.scopedPropertyName⏎··············}\`·map·to·\`${urlKey}\`.·You·can·fix·this·by·mapping·one·of·the·controller·properties·to·a·different·query·param·key·via·the·\`as\`·config·option,·e.g.·\`${⏎················qpOther.prop⏎··············` with `qpOther.scopedPropertyName}\`·and·\`${qp.scopedPropertyName}\`·map·to·\`${urlKey}\`.·You·can·fix·this·by·mapping·one·of·the·controller·properties·to·a·different·query·param·key·via·the·\`as\`·config·option,·e.g.·\`${qpOther.prop`  prettier/prettier
  1070:89   error  Replace `⏎············qp.route.routeName⏎··········` with `qp.route.routeName`                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              prettier/prettier
/home/travis/build/emberjs/ember.js/packages/@ember/-internals/runtime/lib/system/core_object.js
  295:38  error  Replace `⏎········this.constructor⏎······` with `this.constructor`  prettier/prettier
/home/travis/build/emberjs/ember.js/packages/@ember/-internals/views/lib/system/jquery.js
  30:16  error  Replace `(jQueryDisabled·?·undefined·:·jQuery)` with `jQueryDisabled·?·undefined·:·jQuery`  prettier/prettier
/home/travis/build/emberjs/ember.js/packages/@ember/object/tests/computed/reduce_computed_macros_test.js
  1535:20  error  Insert `(`  prettier/prettier
  1541:10  error  Insert `)`  prettier/prettier
/home/travis/build/emberjs/ember.js/packages/internal-test-helpers/lib/ember-dev/method-call-tracker.ts
  164:143  error  Replace `⏎············actual[0]⏎··········` with `actual[0]`  prettier/prettier
  171:143  error  Replace `⏎············actual[0]⏎··········` with `actual[0]`  prettier/prettier
✖ 15 problems (15 errors, 0 warnings)
  15 errors and 0 warnings potentially fixable with the `--fix` option.
```

Can you run `yarn lint:fix`?

2019-06-09 13:19 UTC, rwjblue requested changes

2019-06-09 13:19 UTC, rwjblue commented on package.json
> +    "prettier": "^1.18.2",
Shouldn't be a dependency, can you move this back down to a devDep?

2019-06-09 23:30 UTC, demersaj commented
I fixed the linter and moved Prettier back to a devDep.

2019-06-10 19:41 UTC, rwjblue approved these changes
Thank you!

2019-06-10 19:42 UTC, merged