[DOC] Added examples for arrayContent[Will|Did]Change
emberjs/ember.js pull request #18306
Opened 2019-08-24 13:55 UTC by mukilane

For #18228 

I've added a basic example for both arrayContentWillChange & arrayContentDidChange. 

I've also added some twiddles to support them.
[arrayContentWillChange](https://ember-twiddle.com/de4000d2daff26396c1b6525d341d307?openFiles=templates.components.my-component.hbs%2Ctemplates.components.my-component.hbs) and [arrayContentDidChange](https://ember-twiddle.com/67cfb2ec4edc9b3aea8cb664bba8ea49?openFiles=templates.components.my-component.hbs%2Ctemplates.components.my-component.hbs)

Would love to have some inputs on how to improve them.

2019-08-25 08:59 UTC, locks requested changes
Left some remarks inline, thanks for the help!

2019-08-25 08:59 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +    ```javascript
Can you give this component a path?

    ```app/templates/show-post.js

Or something like that

2019-08-25 08:59 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +    ```javascript
You are missing the imports in this code block.

2019-08-25 08:59 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +
```suggestion
```

2019-08-25 08:59 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +        this._super(...arguments);
```suggestion
        this._super(...arguments);

```

2019-08-25 08:59 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +          this.posts.arrayContentWillChange(); // attemptsToModify = 1
You are not passing any of the two required params to `arrayContentWillChange`, can you update?

2019-08-25 11:42 UTC, mukilane commented
@locks , I've updated them.

2019-08-30 16:00 UTC, mukilane commented
@locks Is any more changes required ?

2019-09-01 02:06 UTC, locks approved these changes
Looking good, let's get it in!

2019-09-01 02:06 UTC, merged