[DOC] Update example for EmberArray#sortBy
emberjs/ember.js pull request #18340
Opened 2019-09-01 14:45 UTC by mukilane

For #18228

Updated the example to include sortBy with multiple keys.

2019-09-01 22:38 UTC, btecu commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +   // [{name: "blue", weight: 500}, {name: "green", weight: 600}, {name: "red", weight: 500}]
Should use `'` consistently

2019-09-02 06:17 UTC, mukilane commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +   // [{name: "blue", weight: 500}, {name: "green", weight: 600}, {name: "red", weight: 500}]
I've updated it.

2019-09-02 07:39 UTC, locks requested changes

2019-09-02 07:39 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +     {name: 'red',  weight: 500 },
```suggestion
     { name: 'red', weight: 500 },
```

2019-09-02 07:39 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +     {name: 'green', weight: 600 },
```suggestion
     { name: 'green', weight: 600 },
```

2019-09-02 07:39 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +     {name: 'blue', weight: 500 }
```suggestion
     { name: 'blue', weight: 500 }
```

2019-09-03 15:25 UTC, mukilane commented
@locks Have updated the requested changes.

2019-09-04 22:04 UTC, locks approved these changes
Thanks for the help!

2019-09-04 22:04 UTC, merged