[DOC] #18228 Update documentation for EmberArray.includes
emberjs/ember.js pull request #18465
Opened 2019-10-04 01:35 UTC by Frozenfire92

#18228

Update documentation for EmberArray.includes

2019-10-05 09:05 UTC, locks requested changes
Left some asks :)

2019-10-05 09:05 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +    [1, 2, 3].includes(3, -1); // true, equivalent to includes(3, 2)
I'm somewhat confused by the comments in here. I would suggest not including them, or having separate example blocks with an explanation included.

2019-10-05 09:05 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
>      This method is a Polyfill for ES 2016 Array.includes.
```suggestion
    This method has the same behavior of JavaScript's [Array.includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes).
```

2019-10-09 12:34 UTC, RobbieTheWagner approved these changes
This seems fine to me. Although, it doesn't really seem to have changed much from what we had before. @locks thoughts?

2019-10-09 13:12 UTC, locks approved these changes
Looks good!

2019-10-09 13:39 UTC, merged

2019-10-09 13:39 UTC, locks commented
Keep up the good work @Frozenfire92 😁