[DOC] #18228 Add example to EmberArray.forEach documentation
emberjs/ember.js pull request #18463
Opened 2019-10-04 01:31 UTC by Frozenfire92

#18228

Adds an example for the EmberArray.forEachmethod

2019-10-05 09:08 UTC, locks requested changes

2019-10-05 09:08 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +      foods.forEach(food => console.log(`You should eat a ${food}`));
Hm, I think we should come up with an example that does some side effect in the `forEach` block, like setting a property in the items of the array.
What if each fruit was an object, and we had an `eaten` property that we toggle to true?

2019-10-26 10:46 UTC, locks submitted a review, later dismissed

2019-10-26 10:46 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +      output += `${index + 1}/${array.length}) ${item}\n`
```suggestion
      output += `${index + 1}/${array.length} ${item.name}\n`;
```

2019-10-26 10:46 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +      { name: carrot': eaten: false }
```suggestion
      { name: 'carrot', eaten: false }
```

2019-10-26 10:46 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +    );
```suggestion
    );
    console.log(output);
    // 1/3 apple
    // 2/3 banana
    // 3/3 carrot
```

2019-10-26 11:21 UTC, locks commented
Left some suggestions :)

2019-11-07 21:40 UTC, pzuraq approved these changes
It looks like the API docs currently use native arrays for a lot of examples. I think this is not ideal, since `EmberArray` is really separate from native arrays (and we want to move more that direction), so in the future we should do a sweep and convert all examples to explicitly use `Ember.A()`, but for now I think this is fine.

2019-11-07 21:42 UTC, merged