[DOC] Update explanation of router service `isActive` method and add code example
emberjs/ember.js pull request #18471
Opened 2019-10-06 15:46 UTC by pauljeannot

Part of #16518

Took the [nice work done](https://github.com/emberjs/ember.js/pull/17622) by @rscotchmer, and updated it with new class syntax.

2019-10-07 15:26 UTC, rwjblue commented on packages/@ember/-internals/routing/lib/services/router.ts
> +     ```javascript return this.get('router').isActive('posts', post.id)```
I think we need some newlines here (after "javascript" and before the ending backticks at least)

2019-10-08 11:22 UTC, locks requested changes
Left some inline asks :)

2019-10-08 11:22 UTC, locks commented on packages/@ember/-internals/routing/lib/services/router.ts
> +     ```app/components/posts.js
```suggestion

     ```app/components/posts.js
```

2019-10-08 11:22 UTC, locks commented on packages/@ember/-internals/routing/lib/services/router.ts
> +     ```javascript return this.get('router').isActive('posts', post.id)```
```suggestion
     
     ```javascript
     return this.get('router').isActive('posts', post.id)
     ```
```

2019-10-08 11:22 UTC, locks commented on packages/@ember/-internals/routing/lib/services/router.ts
> +     ```javascript return this.get('router').isActive('posts', post.id)```
We also try to make the code samples as complete as possible. Can you add some more context to it so it's easier to understand where it goes?

2019-11-09 00:02 UTC, pzuraq reviewed
This generally looks good, just need to fix the formatting around the examples (per @locks suggestions). More context for the examples would be good as well.

2020-01-14 11:26 UTC, locks commented
Thank you for your help!

2020-01-14 11:26 UTC, merged