[DOC] Glimmer Component & Tracking docs to target Octane release
emberjs/ember.js pull request #18518
Opened 2019-10-25 00:59 UTC by jenweber

This is ready for preliminary review, but should not be merged yet.

2019-11-08 23:55 UTC, jenweber commented
This is something that still needs help from other knowledgeable people in order to get it over the finish line. @tomdale can you help out with this one?

2019-11-12 01:46 UTC, pzuraq requested changes

2019-11-12 01:46 UTC, pzuraq commented on packages/@ember/-internals/glimmer/lib/glimmer-component-docs.ts
> +`didInsertElement` is called when the component has been inserted into the DOM.
This is only available in Glimmer.js apps, we should not include it in the API docs for Ember. It'll be removed soon.

2019-11-12 01:46 UTC, pzuraq commented on packages/@ember/-internals/glimmer/lib/glimmer-component-docs.ts
> +@method didUpdate
This is only available in Glimmer.js apps, we should not include it in the API docs for Ember. It'll be removed soon.

2019-11-14 02:11 UTC, jenweber reviewed
Small stylistic suggestions.

2019-11-14 02:11 UTC, jenweber commented on packages/@ember/-internals/glimmer/lib/glimmer-component-docs.ts
> +    @service animation;
```suggestion
    @service myAnimations;
```

I have found it useful to preface things that aren't built into Ember with `my` or `custom` in order to help new people who don't know where the boundaries are.

2019-11-14 02:11 UTC, jenweber commented on packages/@ember/-internals/glimmer/lib/glimmer-component-docs.ts
> +        this.animation.register(this, 'fade-in');
```suggestion
        this.myAnimations.register(this, 'fade-in');
```

2019-11-14 02:11 UTC, jenweber commented on packages/@ember/-internals/glimmer/lib/glimmer-component-docs.ts
> +  cleanup the component and any related state.
```suggestion
  cleanup the component and any related state, such as polling functions or websocket connections.
```

2019-11-14 02:11 UTC, jenweber commented on packages/@ember/-internals/glimmer/lib/glimmer-component-docs.ts
> +    @service animation;
```suggestion
    @service myAnimations;
```

2019-11-14 02:11 UTC, jenweber commented on packages/@ember/-internals/glimmer/lib/glimmer-component-docs.ts
> +      this.animation.unregister(this);
```suggestion
      this.myAnimations.unregister(this);
```

2019-11-14 03:05 UTC, jenweber commented
Unfortunately there is not a nice way to show an `@property` on a module. They can only go on Classes, which would add more noise to the table of contents. So, I moved all the API methods and properties into the module description for `@glimmer/component`. `tracked` is done "correctly."

![Screenshot_2019-11-13  glimmer component - 3 18 - Ember API Documentation](https://user-images.githubusercontent.com/16627268/68823402-a8b12f00-0661-11ea-87d5-91059aabcfb7.png)
![Screenshot_2019-11-13  glimmer tracking - 3 18 - Ember API Documentation](https://user-images.githubusercontent.com/16627268/68823413-ad75e300-0661-11ea-96a8-ce81fd9002e3.png)
![Screenshot_2019-11-13 tracked - 3 18 - Ember API Documentation](https://user-images.githubusercontent.com/16627268/68823416-afd83d00-0661-11ea-9085-206bdedcb78d.png)

2019-11-15 20:19 UTC, rwjblue approved these changes

2019-11-15 21:13 UTC, pzuraq approved these changes

2019-11-15 21:14 UTC, merged