Document a contrived example for EmberArray#filter target option
emberjs/ember.js pull request #18789
Opened 2020-02-28 23:35 UTC by mehulkar

Closes #18522

cc @locks

2020-02-29 09:20 UTC, locks requested changes
one small ask. ember resources generally use ["liberal let"](https://madhatted.com/2016/1/25/let-it-be) style.

2020-02-29 09:20 UTC, locks commented on packages/@ember/-internals/runtime/lib/mixins/array.js
> +    const collection = new AdultsCollection({ engineering: true });
```suggestion
    let collection = new AdultsCollection({ engineering: true });
```

2020-02-29 16:48 UTC, mehulkar commented
np, updated :)

2020-03-07 11:57 UTC, locks approved these changes

2020-03-07 11:57 UTC, merged

2020-03-07 11:57 UTC, locks commented
Thanks!