[BUGFIX lts] Ensures that tracked properties initialize property
emberjs/ember.js pull request #19172
Opened 2020-09-30 18:48 UTC by pzuraq

Fixes tracked property initialization for classic classes.

2020-09-30 19:11 UTC, rwjblue requested changes

2020-09-30 19:11 UTC, rwjblue commented on packages/@ember/-internals/runtime/lib/system/core_object.js
> +        obj[keyName] = value;
Chatted with @pzuraq about this, he is going to bring back the prior code (to avoid looking up the descriptor _again_).

2020-09-30 20:01 UTC, rwjblue approved these changes

2020-09-30 20:15 UTC, merged

2020-10-02 20:45 UTC, ef4 commented
This caused an app failure in the wild, see https://github.com/emberjs/ember.js/issues/19179