Add {{page-title}} to route templates
emberjs/ember.js pull request #19224
Opened 2020-10-23 13:03 UTC by raido

Changes in this PR are for `ember-page-title` RFC - https://github.com/ember-cli/ember-cli/issues/9370

Related PR for `ember-cli`: https://github.com/ember-cli/ember-cli/pull/9372

2020-10-23 13:23 UTC, rwjblue requested changes
Can you add some logic to the blueprint to detect if the app has `ember-page-title` installed, and only add the `{{page-title ...}}` invocation when it is?

2020-10-23 13:25 UTC, raido commented
> Can you add some logic to the blueprint to detect if the app has `ember-page-title` installed, and only add the `{{page-title ...}}` invocation when it is?

Sure, first I am just trying to get current test suite green and then add additional logic :)

2020-10-23 13:44 UTC, raido commented
Failed with weird some TypeError - https://github.com/emberjs/ember.js/pull/19224/checks?check_run_id=1298266214#step:7:109 - not sure if related or not @rwjblue ?

2020-10-23 16:06 UTC, raido commented on blueprints/route/files/__root__/__templatepath__/__templatename__.hbs
> +<% if (addTitle) {%>{{page-title "<%= routeName %>"}}
Syntax is like this to keep whitespace consistent.

2020-10-23 16:33 UTC, raido commented
CI failure seems to be same with master branch.

2020-10-23 17:20 UTC, raido commented
Actually, I am tempted to reverse test setup logic. So all previous tests would remain unchanged and "ember-page-title installed" cases are added. It is then much less changes.

2020-10-23 17:20 UTC, rwjblue commented
I believe https://github.com/emberjs/ember.js/pull/19225 will resolve that.

2020-10-23 19:05 UTC, raido commented
@rwjblue Rebased on master, CI green and tests refactored.

2020-10-24 23:07 UTC, rwjblue approved these changes

2020-10-24 23:08 UTC, merged

2020-10-24 23:08 UTC, rwjblue commented
Thanks @raido!