[BUGFIX] Update VM, fix component name preprocessing
emberjs/ember.js pull request #19363
Opened 2021-01-30 05:15 UTC by pzuraq

2021-01-30 14:53 UTC, rwjblue requested changes

2021-01-30 14:53 UTC, rwjblue commented on packages/@ember/-internals/glimmer/lib/environment.ts
> +      let override = VM_ASSERTION_OVERRIDES.find((o) => o.id === id);
Can't use `.find` on IE11 (this is failing browser stack)

2021-01-30 14:53 UTC, rwjblue commented on packages/@ember/-internals/glimmer/lib/environment.ts
> +      let override = VM_ASSERTION_OVERRIDES.find((o) => o.id === id);
I think we should probably change the overrides to be a map / pojo where the key is the `id`.  What do you think?

2021-01-30 14:53 UTC, rwjblue commented on packages/@ember/-internals/glimmer/lib/environment.ts
> +      let override = VM_DEPRECATION_OVERRIDES.find((o) => o.id === id);
Same here RE: `.find`

2021-02-01 17:42 UTC, jamescdavis commented
Fixes #19360

2021-02-01 20:27 UTC, rwjblue approved these changes

2021-02-01 20:27 UTC, merged