Deprecate auto location
emberjs/ember.js pull request #19510
Opened 2021-04-27 18:50 UTC by sandstrom

Work to implement the [Deprecate Auto Location RFC](https://github.com/emberjs/rfcs/blob/master/text/0711-deprecate-auto-location.md).

### TODO

- [ ] Make sure the code works (I haven't run it yet)
- [ ] Modify deprecation messages (if needed?)
- [ ] Add an entry into the Ember deprecation table (guides repo?)

2021-04-30 10:55 UTC, Windvis commented
@sandstrom I think you can use the [`expectDeprecation` test helper](https://github.com/emberjs/ember.js/blob/21bd70c773dcc4bfe4883d7943e8a68d203b5bad/packages/internal-test-helpers/lib/ember-dev/deprecation.ts#L28), that would also test if the deprecations are working correctly :smiley:.

2021-05-24 14:59 UTC, rwjblue commented
This looks good overall. I think once we have some tests, we should be good to go.

2021-07-17 12:11 UTC, mixonic commented on packages/@ember/-internals/routing/lib/location/api.ts
> +        until: '4.0.0',
```suggestion
        until: '5.0.0',
```

2021-07-17 12:12 UTC, mixonic commented on packages/@ember/-internals/routing/lib/location/api.ts
> +          enabled: '3.28.1',
```suggestion
          enabled: '4.0.0',
```

2021-07-17 12:14 UTC, mixonic commented on packages/@ember/-internals/routing/lib/system/router.ts
> +            until: '4.0.0',
```suggestion
            until: '5.0.0',
```

2021-07-17 12:14 UTC, mixonic commented on packages/@ember/-internals/routing/lib/system/router.ts
> +              enabled: '3.28.1',
```suggestion
              enabled: '4.0.0',
```

2021-07-17 12:14 UTC, mixonic commented on packages/@ember/-internals/routing/lib/system/router.ts
> +              until: '4.0.0',
```suggestion
              until: '5.0.0',
```

2021-07-17 12:14 UTC, mixonic commented on packages/@ember/-internals/routing/lib/system/router.ts
> +                enabled: '3.28.1',
```suggestion
                enabled: '4.0.0',
```

2021-07-17 12:18 UTC, mixonic requested changes
@sandstrom I'm sorry we didn't manage to get this landed before 4.0. It seems like it was pretty close, and then summer hours hit and this fell off our radar. I really appreciate the effort you put in.

Can you tweak this and the deprecation guide PR to target 5.0?

2021-09-04 17:30 UTC, sandstrom commented
@mixonic I've updated the PR to target 5.0.0. I set the since/enabled value to 4.1.0, since I think 4.0.0 may be released soon, and possibly before anyone has had time to merge this.

But let me know if you want to drop this down to 4.0.0 for the since/enabled value.

2021-11-05 19:04 UTC, rwjblue approved these changes

2021-11-05 19:04 UTC, merged