Remove @ember/string methods from native prototype
emberjs/ember.js pull request #19654
Opened 2021-07-18 19:54 UTC by mixonic

Deprecated API removal per https://github.com/emberjs/ember.js/issues/19617

2021-07-21 15:55 UTC, rwjblue requested changes
Also needs to remove these things:

https://github.com/emberjs/ember.js/blob/ff1603207e2e255be69968654908f45cfbc18eee/packages/%40ember/-internals/environment/lib/env.ts#L40

https://github.com/emberjs/ember.js/blob/ff1603207e2e255be69968654908f45cfbc18eee/packages/%40ember/-internals/environment/lib/env.ts#L221

https://github.com/emberjs/ember.js/blob/ff1603207e2e255be69968654908f45cfbc18eee/packages/%40ember/-internals/environment/lib/env.ts#L225

2021-07-21 15:55 UTC, rwjblue commented
> As such, this also does not completely remove ENV.EXTEND_PROTOTYPES.String

Hmph. This is unfortunate. 🤔

2021-07-21 16:27 UTC, locks commented
> Hmph. This is unfortunate. 🤔

I've added to this week's agenda so we have a think.

2021-07-22 00:18 UTC, mixonic commented
@rwjblue I can't do those removals until we are sure we can remove `htmlSafe`, right? This PR could land as-is, and we could do the `htmlSafe` removal and complete removal of `EXTEND_PROTOTYPES.String` in another PR.

Or we can block this until we figure out the path for `htmlSafe`. I'd rather decouple and just land this, but your review can make the call.

2021-07-31 18:27 UTC, mixonic commented
At the July 23rd Ember Framework Core meeting we agreed that `String.prototype.htmlSafe` was intended to be deprecated. We don't expect it is in very high use across the Ember community, and we're comfortable expanding the string prototype deprecation to include it in a point release for 3.27 and in 3.28.0.

This PR should include `String.prototype.htmlSafe` in its removals, but before this is merged we should first write and land the PR to add it to the deprecations.

2021-08-01 18:14 UTC, mixonic commented on packages/@ember/-internals/environment/lib/env.ts
> -    Function: true,
There are two commits in this PR, and the first makes this unrelated change to remove `Function` from this list and docs. The code deletion for function methods on prototype was done at https://github.com/emberjs/ember.js/pull/19663 but this removal was missed.

2021-08-17 00:56 UTC, kategengler approved these changes

2021-08-17 00:58 UTC, merged