Add docs for low-level apis (and new apis since 3.25)
emberjs/ember.js pull request #19953
Opened 2022-02-10 15:52 UTC by NullVoxPopuli

2022-02-10 16:49 UTC, chriskrycho commented on packages/@ember/component/index.ts
> + * @param {'3.4' | '3.13'} managerApiVersion
I *believe* this has to be `3.13` for Ember v4?

2022-02-10 16:49 UTC, chriskrycho reviewed
Thanks very much for opening this!

2022-02-10 22:29 UTC, wagenet commented
Might be some overlap with #19948.

2022-02-25 02:23 UTC, chriskrycho commented
@NullVoxPopuli mind rebasing this and addressing the comment above? (The rebase doesn’t look strictly necessary but given the amount of change it’d make me more confident in the results here!)

2022-02-25 02:27 UTC, NullVoxPopuli commented
@chriskrycho done. thanks!

2022-04-06 18:12 UTC, chriskrycho requested changes

2022-04-06 18:12 UTC, chriskrycho commented on packages/@ember/component/index.ts
> +export const getComponentTemplate = _getComponentTemplate;
As above!

2022-10-28 21:04 UTC, chriskrycho commented
@NullVoxPopuli still interested in landing these docs updates?

2022-10-29 04:00 UTC, NullVoxPopuli commented
@chriskrycho updated!

2023-08-04 16:13 UTC, locks commented
@NullVoxPopuli is this still relevant?

2023-08-04 16:43 UTC, NullVoxPopuli commented
Yup

2023-08-04 16:47 UTC, NullVoxPopuli commented
Ember helper is also missing a bunch of docs

2023-12-12 16:42 UTC, kategengler commented
@NullVoxPopuli If this is still relevant, do you want to update it?

2023-12-12 19:12 UTC, NullVoxPopuli commented
Yes, this documentation has been missing for a long time :upside_down_face: update incoming

2023-12-12 19:30 UTC, kategengler commented
Enabled auto-merge, thank you!

2023-12-12 20:14 UTC, merged