[WIP] Type export experimentation
emberjs/ember.js pull request #20003
Opened 2022-03-03 18:41 UTC by wagenet

2022-03-28 17:48 UTC, chriskrycho requested changes
Couple of nits from the modules affected, will deeply-read-and-understand `build-docs.js` next.

2022-03-31 15:53 UTC, wagenet commented on packages/@ember/-internals/runtime/lib/system/core_object.d.ts
> -/** @internal */
Good question. I'll need to look into it more.

2023-08-04 16:14 UTC, locks commented
I see a lot of conflicts. Has the work been done elsewhere?

2023-12-12 16:17 UTC, kategengler commented
Is this still relevant? It is a draft PR

2023-12-16 03:45 UTC, chriskrycho commented
I *believe* this was superceded in its entirety by #20449 (as well as the foundational PRs which preceded it); this was Peter's admirable first pass at trying to get types publishing, and was invaluable prior art in informing the Ember TypeScript team that we were going to have to do the *absolute shenanigans* that we did in #20449 to get things published. Closing accordingly!

2023-12-16 03:45 UTC, closed without merging