[DOC] Reformatting Ember API docs for Typescript - proxy-mixin-interface
emberjs/ember.js pull request #20192
Opened 2022-09-11 20:19 UTC by TechieQian

In response to https://github.com/emberjs/ember.js/issues/20172.

2022-09-20 21:36 UTC, ttbach approved these changes

2022-09-22 14:56 UTC, chriskrycho requested changes
Thanks for doing this! Looks good overall, but the doc comments on the `interface` need to include *all* of the original doc comments from the `Mixin` definition. Please copy over the things like `@property`, `@default`, and `@public`, or the doc generator won't work correctly. Also, please remove the corresponding doc comments from the mixin entirely. Thanks!

2022-09-22 17:03 UTC, TechieQian commented
Sounds good! done

2022-09-23 12:32 UTC, chriskrycho approved these changes
Thanks for making the changes here!

2022-09-23 12:43 UTC, merged