Move @ember/polyfill types to stable
emberjs/ember.js pull request #20325
Opened 2022-12-17 21:46 UTC by theroncross

toward #19946

2022-12-19 18:25 UTC, chriskrycho requested changes
Excellent! This also needs the corresponding entries (and files!) removed from the preview types. Once you do that, ping me and I'll re-review and land it. Thank you!

2022-12-20 02:49 UTC, theroncross commented
Ah, that step is missing from https://github.com/emberjs/ember.js/issues/19946#issuecomment-1330635787

In this case, the preview types are an improvement over the source types. However, they have a dependency on the `Mix` types from `/types/preview/@ember/polyfills/types.d.ts`, which don't seem to be used anywhere else. Do you have a preference for where one-off utility types live?

2023-01-18 23:51 UTC, chriskrycho commented
@theroncross are you still up to finish updating this? Would love to land it!

2023-01-19 03:13 UTC, theroncross commented
Sorry about that. Got sidetracked by life a bit.

The tests needed some changes to match the `Object.assign` type behavior, but it should be close now.

2023-01-20 02:41 UTC, chriskrycho commented
Sweet, will take a look tomorrow, and just re-approved CI! Thank you!

2023-01-21 16:36 UTC, chriskrycho approved these changes

2023-01-21 16:36 UTC, chriskrycho commented on packages/@ember/polyfills/lib/assign.ts
> +export function assign(target: object, ...sources: any[]): any;
:sigh: This is probably the “right” thing to do here, since it’s what TS itself has, but I hate it.

2023-01-21 16:37 UTC, chriskrycho commented
@theroncross looks good overall but I think some of the type tests will need updating!

2023-03-21 03:47 UTC, chriskrycho commented
@theroncross I think we're going to end up closing this as "not needed" since it's all removed as of Ember v5. Thank you again, though!

2023-03-21 03:47 UTC, closed without merging

2023-03-21 03:48 UTC, chriskrycho commented
Superseded here specifically by #20380.